var questions = {};
questions.cs = [
    "Nikdy jsem nebyl(a) omylem zastaven(a) policií.",
    "Nikdy jsem sněhulákovi neudělal(a) prsa s pinďourem.",
    "Nikdy jsem nezažil(a), že by mi v práci proplatili celý den, aniž bych musel(a) hnout prstem.",
    "Nikdy jsem nebyl(a) náměsíčný/á.",
    "Nikdy jsem nepřistihl(a) své rodiče při sexu.",
    "Nikdy jsem si do čaje nedal(a) místo cukru sůl.",
    "Nikdy jsem neměl(a) nic zlomeného.",
    "Nikdy jsem neměl(a) rád(a), nebo nepil(a) rajčatový džus.",
    "Nikdy jsem omylem hlavou nerozbil(a) lustr.",
    "Nikdy jsem neomdlel(a).",
    "Nikdy jsem neposiloval(a).",
    "Nikdy jsem na sobě neměl(a) pyžamo.",
    "Nikdy jsem nic nesbíral(a) (např. známky).",
    "Nikdy jsem si nepodal(a) ruku s celebritou.",
    "Nikdy jsem nezažil(a), že by mě ve spánku pozvracel pes.",
    "Nikdy jsem neulovil(a) živou rybu.",
    "Nikdy jsem si nevyrazil(a) dech.",
    "Nikdy jsem netoužil(a) po sexu s nějakou celebritou.",
    "Nikdy jsem neviděl(a) živou světlušku.",
    "Nikdy jsem neviděl(a) ducha, ani nezažil(a) nic jiného, nadpřirozeného.",
    "Nikdy jsem v životě nemusel(a) bojovat o život.",
    "Nikdy jsem se nenaučil(a) lyžovat.",
    "Nikdy jsem nebyl(a) na Slovensku.",
    "Nikdy jsem si nepřivřel(a) prst do dveří.",
    "Nikdy jsem nevyrazil(a) na nákup omylem bez peněz.",
    "Nikdy jsem nevykouřil(a) víc jak 3 cigarety denně.",
    "Nikdy jsem omylem nesnědl(a) mouchu.",
    "Nikdy jsem nebyl(a) vzrušený/á z toho, když někdo okolo mě měl sex.",
    "Nikdy jsem po silnici (mimo dálnici) nejel(a) víc jak 100 km/hod.",
    "Nikdy jsem nechodil(a) po bytě v botech od bláta.",
    "Nikdy jsem se jen tak nepodíval(a) na porno.",
    "Nikdy jsem na vysvědčení neměl(a) horší známku než trojku.",
    "Nikdy jsem nejedl(a) žádné zvíře zaživa.",
    "Nikdy jsem nikomu nic neudělal(a) ve spánku (např. pomalování obličeje).",
    "Nikdy jsem nezažil(a) jídlo při svíčkách.",
    "Nikdy jsem na nikoho nenalíčil(a) past.",
    "Nikdy jsem si nezkazil(a) účes tím, že jsem se vlastoručně ostříhal(a).",
    "Nikdy jsem se na veřejnosti nekoupal(a) mezi lidmi nahý/á (mimo dětství).",
    "Nikdy jsem minimálně do pěti let nevěděl(a) o tom, že existuje sex.",
    "Nikdy jsem nebyl(a) vzhůru déle než 48 hodin.",
    "Nikdy jsem nedokázal(a) nejíst víc jak 24 hodin.",
    "Nikdy jsem si ilegálně nestáhl(a) nějakou věc.",
    "Nikdy jsem si v životě nerozbil(a) víc jak 2 mobily.",
    "Nikdy jsem nevyhodil(a) svůj mobil do dáli a totálně ho nerozsekal(a).",
    "Nikdy jsem nezjistil(a), jak obratně nakrájet cibuli na kostičky.",
    "Nikdy jsem se se svým/svou dosavadní nejlepší kamarádkou/kamarádem nepohádal(a).",
    "Nikdy jsem neudělal(a) to, že bych nalezenou peněženku nevrátil(a), nebo nenahlásil(a).",
    "Nikdy jsem se nesnažil(a) někoho opít.",
    "Nikdy jsem neměl(a) kamaráda/kamarádku, co by jeli na drogách (těžších než marihuana).",
    "Nikdy jsem nešmíroval(a) někoho nahého pod vodou.",
    "Nikdy jsem si nechatoval(a) s jinými lidmi během sexu.",
    "Nikdy jsem neměl(a) pohlavní nemoc.",
    "Nikdy jsem neprojížděl(a) svému nejlepšímu kamarádovi/kamarádce mobil (aniž by o tom věděl(a)).",
    "Nikdy jsem úmyslně nesnědl(a) nic zkaženého.",
    "Nikdy jsem nebyl(a) na rande s více jak jedním člověkem.",
    "Nikdy jsem se neopil(a) do bezvědomí.",
    "Nikdy jsem si nic nekupoval(a) v sexshopu.",
    "Nikdy jsem se nechlubil(a), že jsem měl(a) sex s někým, když to nebyla pravda.",
    "Nikdy jsem nezažil(a), že by mi někdo nabídl, že by se mnou chtěl mít sex (počítá se i partner).",
    "Nikdy jsem se po 12. roce života nevyčůral(a) do bazénu.",
    "Nikdy jsem nezkoušel(a) tvrdší drogy, než je tráva.",
    "Nikdy jsem si nevolal(a) s někým během sexu.",
    "Nikdy jsem z legrace fyzicky neubližoval(a) zvířatům.",
    "Nikdy jsem nic naschvál v práci nerozbil(a).",
    "Nikdy jsem nepodvedl(a) svou polovičku.",
    "Nikdy jsem nikomu nezůstal(a) dlužníkem peněz.",
    "Nikdy jsem se na internetu nevydával(a) za někoho jiného.",
    "Nikdy jsem si během sprchování nepořizoval(a) selfie.",
    "Nikdy jsem neměl(a) víc jak 10 sexuálních partnerů.",
    "Nikdy jsem nepoužíval(a) vlastoručně vyráběnou, erotickou hračku.",
    "Nikdy jsem nepředstíral(a), že se s kamarády dobře bavím a potom je druhý den nepomlouval(a).",
    "Nikdy jsem před jiným člověkem ze srandy neponížil(a) svého nejlepšího kamaráda/kamarádku.",
    "Nikdy jsem se s dítětem nekoukal(a) na nic erotického.",
    "Nikdy jsem nezvracel(a) ožralý/á ve spánku.",
    "Nikdy jsem sexuálně nezneužil(a) partnera, zatímco spal.",
    "Nikdy jsem si nefotil(a) svoje přirození.",
    "Nikdy jsem nespal(a) s nikým pod 13 let.",
    "Nikdy jsem nikomu neukradl(a) peníze.",
    "Nikdy jsem nikomu neplivl(a) do jídla.",
    "Nikdy jsem nedal(a) živého tvora do mikrovlnky a tím nezabil(a).",
    "Nikdy jsem svému nejlepšímu kamarádovi nepřebral(a) partnera.",
    "Nikdy jsem nebyl(a) sprostý/á na svoje rodiče.",
    "Nikdy jsem za zády nepomlouval(a) svého nejlepšího kamaráda/kamarádku, i když jsem se před ním tvářil(a), že je vše v pořádku.",
    "Nikdy jsem nikomu neřekl(a), že spousta mých vztahů byl(a) jen kvůli tomu, abych nebyl(a) v životě bez partnera.",
    "Nikdy jsem na nikoho úspěšně nehodil(a) svůj velký prohřešek.",
    "Nikdy jsem naschvál malému dítěti nedal(a) něco odporného k jídlu, co normální lidi nejedí (např. hmyz).",
    "Nikdy jsem nepomyslel(a) na to, že bych zahnul(a) své dosavadní polovičce.",
    "Nikdy jsem neměl(a) sex s člověkem, který nevěděl, že trpím pohlavní nemocí.",
    "Nikdy jsem nebyl(a) na testu proti HIV i když jsem měl(a) více jak 15 sexuálních partnerů.",
    "Nikdy jsem nikomu neřekl(a) o pravdě, že mě sexuálně přitahuje stejné pohlaví.",
    "Nikdy jsem nikomu neřekl(a), že bych nechtěl(a) mít děti i když je to pravda.",
    "Nikdy jsem neměl(a) v úmyslu dát peníze na charitu i když bych měl(a) na účtě více jak 100 milionů korun.",
    "Nikdy jsem nikomu neřekl(a), že nemám moc kamarádské pouto se svými rodiči, i když je to pravda.",
    "Nikdy jsem s někým nespal(a) jen kvůli tomu, abych zahnal(a) svoje sexuální choutky, i když si o mně dotyčný myslel něco jiného.",
    "Nikdy jsem nikomu neřekl(a) &#8220;miluji tě&#8221;.",
    "Nikdy jsem se v dospělosti nerozbrečel(a) u doktora.",
    "Nikdy jsem nedokázal(a) všem svým nejbližším říct, že mám nějaké fyzické postižení.",
    "Nikdy jsem nepomyslel(a) na to, že bych chtěl(a), aby někdo z mé rodiny zemřel, abych měl(a) nárok na nemovitost.",
    "Nikdy jsem nešířil(a) největší tajemství toho, kdo mi věřil.",
    "Nikdy jsem v análu neměl(a) žádnou erotickou pomůcku.",
    "Nikdy jsem se na záchodě neutřela ruličkou od papíru.",
    "Nikdy jsem nepředváděla nějaký klip když jsem byl/a sama doma.",
    "Nikdy jsem nehodil odpadek do trávy.",
    "Nikdy jsem neměl pohlavní styk.",
    "Nikdy jsem si nečistil zuby prstem.",
    "Nikdy jsem neukradl peníze.",
    "Nikdy jsem nešáhl opačému pohlaví za zadek.",
    "Nikdy jsem se nechtěl vyspat s youtuberem.",
    "Nikdy jsem neřekl sprosté slovo před učitelem.",
    "Nikdy jsem kamarádovi nepoblil boty (xD).",
    "Nikdy jsem nedal opačnému pohlaví facku.",
    "Nikdy jsem neběhal nahý po domě, bytě.",
    "Nikdy jsem neukradl něco na návštěvě.",
    "Nikdy jsem nezkoušel odemknout mobil jazykem.",
    "Nikdy jsem si pořádně nahlas neprdl na veřejnosti.",
    "Nikdy jsem se nepozvracel na silvestra.",
    "Nikdy jsem neviděl youtubera.",
    "Nikdy jsem nenadával na oblíbeného youtubera.",
    "Nikdy jsem neměl nejvíc likeovaný komentář u videa.",
    "Nikdy jsem netočil video na youtube.",
    "Nikdy jsem neměl děsnou chut na něco co nemám rád.",
    "Nikdy jsem neusnul u filmu.",
    "Nikdy jsem nechtěl utéct z domu.",
    "Nikdy jsem nezkoušel helium.",
    "Nikdy jsem se nepohádal v obchodě se zaměstanavatelem. (hlídačkou,prodavačkou)",
    "Nikdy jsem neměl myšlenku o tom že se zabiju.",
    "Nikdy jsem se nepočural smíchy.",
    "Nikdy jsem neměl pindíka. (xD)",
    "Nikdy jsem se nevyčural do vany nebo do sprchy.",
    "Nikdy jsem si nedával nohy za hlavu.",
    "Nikdy jsem si nečuchl k mému prdu.",
    "Nikdy jsem nedal dislike Gogovy.",
    "Nikdy jsem na sobě neměl make-up.",
    "Nikdy jsem neutopil rybu.",
    "Nikdy jsem se pořádně nevykakal.",
    "Nikdy jsem nebyl v kině na hororu.",
    "Nikdy jsem se nevysmrkal do ponošky.",
    "Nikdy jsem nedělal balonky z kondomů..",
    "Nikdy jsem nepromluvil rasisticky.",
    "Nikdy jsem neurážel Miloše Zemana.",
    "Nikdy jsem nekouřil.",
    "Nikdy jsem se nelíbal se stejným pohlavím.",
    "Nikdy jsem se nelíbal se spolužákem.",
    "Nikdy jsem nehrál Minecraft.",
    "Nikdy jsem neměla záchvat smíchu z videií FattyhoPillowa.",
    "Nikdy jsem nezpíval song od Mishovy Šílenosti.",
    "Nikdy jsem nikomu nedal přes držku.",
    "Nikdy jsem nedostal přes držku."
];
questions.en = [
    "Never have I ever gone skinny dipping.",
    "Never have I ever gone on a blind date.",
    "Never have I ever creeped an ex on social media.",
    "Never have I ever been hungover.",
    "Never have I ever kissed my best friend.",
    "Never have I ever ghosted someone.",
    "Never have I ever gotten a speeding ticket.",
    "Never have I ever slid into someone's DMs.",
    "Never have I ever dined and dashed.",
    "Never have I ever used a fake ID.",
    "Never have I ever had a crush on a teacher.",
    "Never have I ever been in love.",
    "Never have I ever made out in a public place.",
    "Never have I ever gotten into a physical fight.",
    "Never have I ever had an alcoholic drink.",
    "Never have I ever played spin the bottle.",
    "Never have I ever snooped through someone's phone.",
    "Never have I ever snuck into a movie theater.",
    "Never have I ever kissed a friend's ex.",
    "Never have I ever told someone \"I love you\" without meaning it.",
    "Never have I ever been called a player.",
    "Never have I ever smoked a cigarette.",
    "Never have I ever given a lap dance.",
    "Never have I ever gotten a lap dance.",
    "Never have I ever cheated on a test.",
    "Never have I ever used a dating app.",
    "Never have I ever kissed more than one person in hours.",
    "Never have I ever cheated on someone.",
    "Never have I ever been cheated on.",
    "Never have I ever sent a racy text to the wrong person.",
    "Never have I ever had a negative bank account balance.",
    "Never have I ever played strip poker.",
    "Never have I ever been arrested.",
    "Never have I ever been expelled.",
    "Never have I ever stolen anything.",
    "Never have I ever gotten a hickey.",
    "Never have I ever been fired.",
    "Never have I ever made out in a movie theater.",
    "Never have I ever dated someone older than me.",
    "Never have I ever dated someone younger than me.",
    "Never have I ever broken the law.",
    "Never have I ever been to a nude beach.",
    "Never have I ever stood a date up.",
    "Never have I ever stayed in a relationship that I really wasn’t feeling.",
    "Never have I ever given someone a fake phone number.",
    "Never have I ever lied to someone in this room.",
    "Never have I ever broken up with someone over text.",
    "Never have I ever had a crush on an SO’s best friend.",
    "Never have I ever shoplifted.",
    "Never have I ever seen a ghost.",
    "Never have I ever told a secret I wasn’t supposed to share.",
    "Never have I ever had a friend with benefits.",
    "Never have I ever intentionally started a fight between other people.",
    "Never have I ever dated more than one person at once.",
    "Never have I ever spent money that wasn’t mine to spend.",
    "Never have I ever had a relationship last less than a month.",
    "Never have I ever had a relationship last longer than a year.",
    "Never have I ever gotten an unexpected piercing.",
    "Never have I ever found a dumb excuse to text an ex.",
    "Never have I ever fallen in love at first sight.",
    "Never have I ever kissed someone I just met.",
    "Never have I ever kept a crush secret from people in this room.",
    "Never have I ever been in love with someone without them knowing.",
    "Never have I ever been in an open relationship.",
    "Never have I ever fantasized about getting back with an ex.",
    "Never have I ever helped a friend lie by being their alibi.",
    "Never have I ever seriously thought about marrying someone.",
    "Never have I ever had a totally online relationship.",
    "Never have I ever flirted just to get something I wanted.",
    "Never have I ever tried guessing someone’s password.",
    "Never have I ever been caught lying.",
    "Never have I ever farted in front of a significant other.",
    "Never have I ever peed in the shower.",
    "Never have I ever peed in a pool.",
    "Never have I ever eaten a carton of ice cream.",
    "Never have I ever cheated in a board game.",
    "Never have I ever cheated in a card game.",
    "Never have I ever screamed during a scary movie.",
    "Never have I ever laughed so hard I spit out my drink.",
    "Never have I ever been sent to the principal's office.",
    "Never have I ever clogged a toilet.",
    "Never have I ever toilet-papered someone's house.",
    "Never have I ever worn something I took out of my dirty laundry.",
    "Never have I ever vomited after a roller coaster ride.",
    "Never have I ever watched an entire television series in a day.",
    "Never have I ever said “I love you” to someone by accident.",
    "Never have I ever walked in on my parents having sex.",
    "Never have I ever lied while playing this game.",
    "Never have I ever Googled myself.",
    "Never have I ever had a pet name for an SO.",
    "Never have I ever been given a pet name by an SO.",
    "Never have I ever had a dirty dream about a super unexpected person.",
    "Never have I ever been accused of sharing too much on social media.",
    "Never have I ever created a fake social media account.",
    "Never have I ever run out of gas while driving.",
    "Never have I ever gone to a party I wasn’t invited to.",
    "Never have I ever dated someone super annoying only because they’re cute.",
    "Never have I ever lied on a first date.",
    "Never have I ever used someone else's toothbrush.",
    "Never have I ever pretended to be on the phone.",
    "Never have I ever enjoyed a smell I’m supposed to find gross.",
    "Never have I ever been on TV for an embarrassing reason.",
    "Never have I ever gone several days without showering.",
    "Never have I ever turned my underwear inside out so I don’t have to wash it.",
    "Never have I ever lied about what I was doing on social media.",
    "Never have I ever been told I snore loudly.",
    "Never have I ever had a crush on a friend's sibling.",
    "Never have I ever eaten a carton of ice cream.",
    "Never have I ever gone commando.",
    "Never have I ever shaved my head.",
    "Never have I ever gotten a tattoo.",
    "Never have I ever broken a bone.",
    "Never have I ever been to a bachelorette party or bachelor party.",
    "Never have I ever gotten heated during a family game night.",
    "Never have I ever met a celebrity.",
    "Never have I ever had a surprise party thrown for me.",
    "Never have I ever travelled solo.",
    "Never have I ever eaten whipped cream straight out of the can.",
    "Never have I ever auditioned for a reality television show.",
    "Never have I ever told my parents I was staying at a friend's house but was really somewhere else.",
    "Never have I ever been to a psychic.",
    "Never have I ever lived alone.",
    "Never have I ever sang karaoke.",
    "Never have I ever stayed overnight in the hospital.",
    "Never have I ever deleted a post because it didn't get enough likes.",
    "Never have I ever stayed up all night.",
    "Never have I ever been on a cruise.",
    "Never have I ever lost a bet.",
    "Never have I ever gotten in a car accident.",
    "Never have I ever rode a motorcycle.",
    "Never have I ever pretended to be sick to get out of school.",
    "Never have I ever beaten a video game.",
    "Never have I ever cried at school.",
    "Never have I ever talked to a family member about my sex life.",
    "Never have I ever been to Mexico.",
    "Never have I ever eaten caviar.",
    "Never have I ever used someone else's Netflix password.",
    "Never have I ever fallen asleep in class.",
    "Never have I ever dyed my hair.",
    "Never have I ever read an entire book in a day.",
    "Never have I ever seen an alligator in real life.",
    "Never have I ever re-gifted a gift.",
    "Never have I ever sleepwalked.",
    "Never have I ever gone snowboarding.",
    "Never have I ever been awake for hours (or more) straight.",
    "Never have I ever broken up with someone in a way I regret.",
    "Never have I ever fainted.",
    "Never have I ever had a fight with a SO in public.",
    "Never have I ever knowingly spread a rumor.",
    "Never have I ever cried at school.",
    "Never have I ever been somewhere I was sure was haunted.",
    "Never have I ever cut my own hair.",
    "Never have I ever lied to get out of plans with friends."
];
questions.pt = [
    "Eu nunca fiquei obcecado em stalkear alguém nas redes sociais.",
    "Eu nunca fui expulso da sala de aula.",
    "Eu nunca desmaiei na rua.",
    "Eu nunca fui parado por policiais.",
    "Eu nunca quebrei um osso.",
    "Eu nunca quebrei um dente.",
    "Eu nunca criei uma conta falsa nas redes sociais.",
    "Eu nunca tive uma experiência paranormal.",
    "Eu nunca tive algum perfil de rede social hackeado.",
    "Eu nunca tive paralisia do sono.",
    "Eu nunca fiquei preso no elevador.",
    "Eu nunca tentei cortar meu próprio cabelo.",
    "Eu nunca pintei o cabelo de alguma cor estranha.",
    "Eu nunca apareci na TV.",
    "Eu nunca passei mal em um parque de diversões.",
    "Eu nunca corri da polícia.",
    "Eu nunca pedi dinheiro no sinal.",
    "Eu nunca me arrependi imediatamente após enviar uma mensagem.",
    "Eu nunca levei um tapa no rosto.",
    "Eu nunca dei um tapa no rosto de alguém.",
    "Eu nunca participei de uma briga.",
    "Eu nunca chorei no transporte público.",
    "Eu nunca passei mais de dois dias sem tomar banho.",
    "Eu nunca olhei o celular de alguém sem que a pessoa soubesse.",
    "Eu nunca fui demitido.",
    "Eu nunca dormi na rua.",
    "Eu nunca consegui algo de graça dando em cima de alguém.",
    "Eu nunca tive um vídeo constrangedor postado na internet.",
    "Eu nunca quebrei algo na casa de alguém e escondi.",
    "Eu nunca saí de uma festa ou bar sem pagar.",
    "Eu nunca me gabei por algo que não fiz.",
    "Eu nunca menti tanto sobre algo que acreditei que fosse verdade.",
    "Eu nunca sofri bullying na escola.",
    "Eu nunca segurei a mão da pessoa errada na rua.",
    "Eu nunca fui expulso de uma festa.",
    "Eu nunca postei algo e me arrependi.",
    "Eu nunca roubei dinheiro da carteira dos meus pais.",
    "Eu nunca comi comida que caiu no chão.",
    "Eu nunca comi comida que alguém largou na área de alimentação do shopping.",
    "Eu nunca fiquei com o irmão/irmã de um amigo.",
    "Eu nunca dormi no ônibus e perdi o meu ponto.",
    "Eu nunca fiquei apaixonado por algum professor.",
    "Eu nunca fui assaltado.",
    "Eu nunca recebi flores.",
    "Eu nunca menti para meus pais sobre onde estava indo.",
    "Eu nunca fiz xixi em uma piscina do lado dos meus amigos.",
    "Eu nunca usei Crocs.",
    "Eu nunca vomitei na frente de outras pessoas.",
    "Eu nunca soltei pum em um elevador e fingi que não fui eu.",
    "Eu nunca segui a pessoa errada na rua.",
    "Eu nunca deixei meu celular cair na privada.",
    "Eu nunca fui em uma festa sem ser chamado.",
    "Eu nunca beijei alguém famoso.",
    "Eu nunca fiquei com gêmeos.",
    "Eu nunca vomitei e tive que engolir.",
    "Eu nunca gostei mais de um filme do que do seu livro.",
    "Eu nunca entrei em casa pela janela.",
    "Eu nunca ri tanto que fiz um pouco de xixi.",
    "Eu nunca menti para alguém sobre qual era meu nome.",
    "Eu nunca tive o meu nome no SPC.",
    "Eu nunca precisei ir ao médico devido a um objeto estranho preso em meu nariz ou ouvido.",
    "Eu nunca usei identidade falsa para entrar em uma festa.",
    "Eu nunca pesquisei meu nome no Google.",
    "Eu nunca dei de presente algo que ganhei e não gostei.",
    "Eu nunca convenci um amigo a largar a namorada.",
    "Eu nunca apaguei um post porque teve poucas curtidas.",
    "Eu nunca usei a escova de dentes de outra pessoa.",
    "Eu nunca me inscrevi em um reality show.",
    "Eu nunca culpei outra pessoa por um erro meu.",
    "Eu nunca menti sobre um candidato em que votei.",
    "Eu nunca dei um conselho ruim para alguém de propósito.",
    "Eu nunca dei em cima do namorado(a) de algum amigo.",
    "Eu nunca disse eu te amo para alguém que eu não amava de verdade.",
    "Eu nunca passei a madrugada mandando mensagem para alguém.",
    "Eu nunca fui ignorado no WhatsApp por alguém que eu gostava.",
    "Eu nunca inventei boatos sobre um(a) ex-namorado(a).",
    "Eu nunca traí alguém.",
    "Eu nunca implorei para algum(a) ex voltar para mim.",
    "Eu nunca estive um relacionamento aberto.",
    "Eu nunca tive um namorado virtual.",
    "Eu nunca me arrependi de ter namorado alguém.",
    "Eu nunca duvidei sobre minha orientação sexual.",
    "Eu nunca namorei uma pessoa para tentar esquecer outra.",
    "Eu nunca sumi depois de um primeiro encontro ruim.",
    "Eu nunca fiquei com alguém comprometido(a).",
    "Eu nunca terminei com alguém por mensagem.",
    "Eu nunca menti sobre meu estado civil.",
    "Eu nunca fingi receber uma mensagem/ligação para sair de um encontro ruim.",
    "Eu nunca falei sobre meu ex em um primeiro encontro.",
    "Eu nunca fiquei com mais de uma pessoa ao mesmo tempo.",
    "Eu nunca dirigi bêbado.",
    "Eu nunca fiquei com uma pessoa e depois nunca mais falei com ela.",
    "Eu nunca vi algum vizinho sem roupa.",
    "Eu nunca usei o Tinder.",
    "Eu nunca fiquei com gêmeos.",
    "Eu nunca marquei de ficar com alguém do Tinder.",
    "Eu nunca fiquei com alguém no banheiro de uma festa.",
    "Eu nunca fiquei com alguém na praia.",
    "Eu nunca fiquei com alguém na rua.",
    "Eu nunca mandei fotos ousadas para alguém.",
    "Eu nunca mandei a mesma foto ousada para duas pessoas ao mesmo tempo.",
    "Eu nunca tive um sonho quente com alguém que está aqui.",
    "Eu nunca tive um sonho quente com algum professor.",
    "Eu nunca fiquei tão louco que esqueci o próprio nome.",
    "Eu nunca fui carregado para casa depois de dar PT.",
    "Eu nunca enviei fotos ousadas para a pessoa errada.",
    "Eu nunca fiquei com alguém na cama dos meus pais.",
    "Eu nunca dancei especialmente para alguém.",
    "Eu nunca usei o Tinder enquanto namorava.",
    "Eu nunca fui num clube para adultos.",
    "Eu nunca faltei ao trabalho porque estava morrendo de ressaca.",
    "Eu nunca fiquei com alguém que eu nem sabia o nome.",
    "Eu nunca fiquei com alguém desta roda.",
    "Eu nunca tirei a roupa em uma festa.",
    "Eu nunca tive um \"amigo colorido\" ou \"amigo com benefícios\".",
    "Eu nunca fiquei com alguém na universidade.",
    "Eu nunca fingi estar sóbrio na frente dos meus pais.",
    "Eu nunca acordei e ainda estava bêbado.",
    "Eu nunca nadei sem roupa em uma praia ou cachoeira.",
    "Eu nunca dei um beijo triplo.",
    "Eu nunca fiquei com alguém em um carro.",
    "Eu nunca beijei alguém depois de ter vomitado.",
    "Eu nunca fui trabalhar bêbado.",
    "Eu nunca dancei em cima de uma mesa.",
    "Eu nunca dei só uma \"passadinha\" na casa do ex ou do crush.",
    "Eu nunca paguei por conteúdos adultos.",
    "Eu nunca recebi fotos ousadas sem estar esperando."
];
questions.fr = [
    "Je n’ai jamais séché l’école ou le travail",
    "Je n’ai jamais fait de moto",
    "Je n’ai jamais perdu un pari",
    "Je n’ai jamais fait de bain de minuit",
    "Je n’ai jamais trompé quelqu’un",
    "Je n’ai jamais chanté au karaoké",
    "Je ne me suis jamais cassé un os",
    "Je n’ai jamais vécu seul(e)",
    "Je n’ai jamais été sur un bateau",
    "Je n’ai jamais conduit une boîte de vitesses manuelle",
    "Je n’ai jamais utilisé de fausse carte d’identité",
    "Je n’ai jamais rompu avec quelqu’un",
    "Je n’ai jamais eu de grosse gueule de bois",
    "Je n’ai jamais embrassé quelqu’un en public",
    "Je ne me suis jamais battu en public",
    "Je n’ai jamais fait l’impasse sur une facture",
    "Je n’ai jamais gagné à la loterie",
    "Je n’ai jamais eu à aller au tribunal",
    "Je n’ai jamais été à un mariage à destination",
    "Je n’ai jamais menti à un patron",
    "Je ne me suis jamais planté à un mariage",
    "Je n’ai jamais embrassé plus d’une personne en heures",
    "Je n’ai jamais fait de farce à quelqu’un",
    "Je n’ai jamais eu d’aventure d’un soir",
    "Je n’ai jamais offert un nouveau cadeau",
    "Je n’ai jamais espionné quelqu’un sur les réseaux sociaux",
    "Je n’ai jamais grimpé par la fenêtre",
    "Je n’ai jamais roulé sur un trottoir",
    "Je n’ai jamais ri au point de faire pipi dans mon pantalon en tant qu’adulte",
    "Je ne suis jamais monté dans le mauvais train ou bus",
    "Je n’ai jamais envoyé de sexto",
    "Je n’ai jamais juré dans un lieu de culte",
    "Je n’ai jamais fouillé dans les affaires de quelqu’un",
    "Je n’ai jamais fumé de la marijuana",
    "Je n’ai jamais passé heures sans me doucher",
    "Je n’ai jamais eu à faire une marche de la honte",
    "Je n’ai jamais pris de vacances en solo",
    "Je n’ai jamais fait de road trip",
    "Je n’ai jamais mangé une pizza entière tout(e) seul(e)",
    "Je n’ai jamais sauvé une vie",
    "Je n’ai jamais eu de tatouage",
    "Je n’ai jamais voulu participer à une émission de télé-réalité",
    "Je n’ai jamais allumé un feu",
    "Je n’ai jamais été arrêté par la sécurité d’un aéroport",
    "Je n’ai jamais été viral en ligne",
    "Je n’ai jamais jeté de chewing-gum dans un espace public",
    "Je n’ai jamais dormi dehors pendant toute une nuit",
    "Je n’ai jamais couru un marathon",
    "Je n’ai jamais donné/reçu un lap dance",
    "Je n’ai jamais fait de discours devant personnes ou plus",
    "Je n’ai jamais fait pipi dans une piscine publique",
    "Je n’ai jamais menti à ma meilleure amie sur la personne avec qui j’étais",
    "Je ne suis jamais allé à Disneyland",
    "Je n’ai jamais fait de plan à trois",
    "Je n’ai jamais laissé quelqu’un en plan",
    "Je ne me suis jamais endormi pendant un rapport sexuel",
    "Je n’ai jamais menti sur mon âge",
    "Je n’ai jamais inventé une histoire sur quelqu’un qui n’était pas vraie",
    "Je n’ai jamais cru que quelque chose était hanté",
    "Je n’ai jamais participé à une manifestation",
    "Je n’ai jamais eu de paralysie du sommeil",
    "Je n’ai jamais été l’alibi d’un ami menteur",
    "Je n’ai jamais fait une nuit blanche",
    "Je n’ai jamais fait de jeu de rôle",
    "Je n’ai jamais regretté une excuse",
    "Je n’ai jamais fait semblant d’être malade pour attirer l’attention",
    "Je n’ai jamais détesté un plat que j’avais cuisiné",
    "Je n’ai jamais supprimé un post sur les réseaux sociaux parce qu’il n’avait pas reçu assez de likes",
    "Je n’ai jamais dépensé plus de euros pour un haut",
    "Je n’ai jamais jeté un verre sur quelqu’un",
    "Je n’ai jamais porté les sous-vêtements de quelqu’un d’autre",
    "Je n’ai jamais voyagé en Europe",
    "Je n’ai jamais tenté un régime à la mode",
    "Je ne suis jamais allé dans un club de strip-tease",
    "Je n’ai jamais regardé une série entière en une journée",
    "Je n’ai jamais essayé les psychédéliques",
    "Je n’ai jamais rencontré quelqu’un de célèbre",
    "Je n’ai jamais fait d’exhibitionnisme",
    "Je n’ai jamais fait partie d’une équipe sportive",
    "Je n’ai jamais dépassé le plafond d’une carte de crédit",
    "Je n’ai jamais été ivre mort(e)",
    "Je n’ai jamais été fiancé(e)",
    "Je ne me suis jamais marié(e)",
    "Je n’ai jamais fait de dons à une organisation caritative",
    "Je n’ai jamais fait semblant d’être malade pour me sortir de quelque chose",
    "Je n’ai jamais posé un lapin à un rendez-vous",
    "Je n’ai jamais ghosté quelqu’un",
    "Je n’ai jamais fait l’amour sur une plage",
    "Je ne suis jamais tombé(e) amoureux(se)",
    "Je n’ai jamais trompé mon partenaire",
    "Je n’ai jamais pris de bain de minuit",
    "Je n’ai jamais fait semblant d’être malade au travail",
    "Je n’ai jamais triché à un examen",
    "Je n’ai jamais mis mon compte en banque à découvert",
    "Je n’ai jamais mangé le repas de quelqu’un d’autre au boulot",
    "Je n’ai jamais joué au strip-poker",
    "Je n’ai jamais fumé un joint",
    "Je n’ai jamais essayé les drogues dures",
    "Je ne me suis jamais endormi dans un lieu public",
    "Je ne me suis jamais endormi au travail",
    "Je n’ai jamais menti sur mon CV",
    "Je n’ai jamais appelé mon ex en état d’ébriété",
    "Je n’ai jamais pris de l’acide",
    "Je n’ai jamais eu un coup d’un soir",
    "Je n’ai jamais lu les messages textes d’un partenaire",
    "Je n’ai jamais lu les courriels d’un partenaire",
    "Je n’ai jamais été hospitalisé(e) pour autre chose que pour accoucher",
    "Je n’ai jamais chanté en public",
    "Je n’ai jamais joué d’un instrument de musique",
    "Je n’ai jamais fait de snowboard",
    "Je n’ai jamais fait de ski",
    "Je n’ai jamais voyagé dans un pays étranger",
    "Je n’ai jamais appris une langue étrangère",
    "Je n’ai jamais accepté un verre d’un étranger",
    "Je n’ai jamais menti sur mes revenus",
    "Je n’ai jamais été pris(e) en flagrant délit dans un lieu public",
    "Je n’ai jamais été nu(e) en public",
    "Je ne suis jamais sorti(e) avec quelqu’un qui avait ans de plus que moi",
    "Je ne suis jamais sorti(e)avec quelqu’un de 5 ans plus jeune",
    "Je n’ai jamais envoyé de SMS ou pris un appel au cinéma",
    "Je n’ai jamais convaincu un ami de larguer son partenaire",
    "Je n’ai jamais convaincu un partenaire de larguer un ami",
    "Je n’ai jamais été l’alibi de quelqu’un d’autre",
    "Je n’ai jamais sauté un tourniquet",
    "Je n’ai jamais éternué(e) sur quelqu’un d’autre au travail",
    "Je n’ai jamais fait don d’un organe",
    "Je n’ai jamais menti à un agent de la force publique",
    "Je n’ai jamais été demoiselle d’honneur",
    "Je n’ai jamais été témoin de mariage",
    "Je n’ai jamais appelé un partenaire par un mauvais nom",
    "Jamais je n’ai pensé que le bébé d’une amie était moche",
    "Je n’ai jamais gagné plus de euros au jeu",
    "Je n’ai jamais perdu plus de euros au jeu",
    "Je n’ai jamais été végétarien(ne)",
    "Je n’ai jamais utilisé de fausse carte d’identité",
    "Je n’ai jamais menti sur mon âge",
    "Je n’ai jamais fait de rêve lucide",
    "Je n’ai jamais fait campagne pour un candidat politique",
    "Je n’ai jamais eu la varicelle",
    "Je n’ai jamais flashé sur quelqu’un",
    "Je n’ai jamais montré mes fesses à quelqu’un",
    "Je n’ai jamais menti à mon meilleur ami",
    "Je n’ai jamais eu un incident de rage au volant",
    "Je n’ai jamais fait exprès de couper la file d’attente",
    "Je n’ai jamais gardé rancune plus d’un an",
    "Je n’ai jamais laissé échapper quelque chose que j’avais juré de garder secret",
    "Je n’ai jamais gâché les vacances de quelqu’un d’autre",
    "Jamais je ne me suis cassé une dent",
    "Je n’ai jamais essayé un régime à la mode",
    "Je ne me suis jamais coupé les cheveux tout(e) seul(e)",
    "Je n’ai jamais été éveillé(e) pendant heures d’affilée ou plus",
    "Je n’ai jamais dit accidentellement « Je t’aime » à quelqu’un",
    "Je n’ai jamais pleuré ou flirté pour éviter une contravention",
    "Je n’ai jamais fouillé dans la chambre, les armoires ou la propriété d’un ami",
    "Je n’ai jamais fait l’amour dans une voiture",
    "Je n’ai jamais travaillé avec quelqu’un que je ne pouvais pas supporter",
    "Je n’ai jamais eu d’ami avec des avantages",
    "Je n’ai jamais mangé de nourriture qui ne respecte pas la règle des cinq secondes",
    "Je n’ai jamais passé une journée entière à regarder la télé-réalité",
    "Je n’ai jamais envoyé de photos de moi nu(e)",
    "Je n’ai jamais reçu de nus",
    "Je n’ai jamais pensé qu’un personnage de dessin animé était sexy",
    "Je n’ai jamais Googlé quelqu’un avant un rendez-vous",
    "Je ne me suis jamais incrusté dans une fête ou un mariage",
    "Je ne suis jamais sortie avec un musicien",
    "Je n’ai jamais eu de rendez-vous à l’aveugle",
    "Je n’ai jamais eu ou donné un suçon",
    "Je ne me suis jamais blessé(e) au lit pendant les galipettes",
    "Je n’ai jamais vu quelqu’un mourir",
    "Je n’ai jamais eu de problème de garde-robe",
    "Je n’ai jamais couru pour ma vie",
    "Je n’ai jamais participé à un concours de talents",
    "Je n’ai jamais eu de points de suture",
    "Je n’ai jamais essayé de rendre un ex jaloux",
    "Je n’ai jamais conduit une boîte de vitesses manuelle",
    "Je n’ai jamais mis le feu à quelque chose en cuisinant",
    "Je n’ai jamais organisé un rendez-vous avec un ami",
    "Je n’ai jamais lancé un hashtag",
    "Je n’ai jamais payé pour du contenu pour adultes",
    "Je n’ai jamais fait de plongée sous-marine",
    "Je n’ai jamais fréquenté quelqu’un du même sexe ou du même genre",
    "Je n’ai jamais espionné en voiture la maison d’un ex ou d’un amoureux",
    "Je n’ai jamais dansé sous la pluie",
    "Je n’ai jamais dansé sur une table",
    "Je n’ai jamais rejoint le mile-high club",
    "Je n’ai jamais dormi dans ma voiture",
    "Je ne suis jamais passé à la télévision",
    "Je n’ai jamais eu d’engelures",
    "Je n’ai jamais eu de coup de soleil brûlant",
    "Je n’ai jamais été malade lors d’un rendez-vous",
    "Je n’ai jamais eu d’empoisonnement alimentaire",
    "Je n’ai jamais donné intentionnellement de mauvais conseils à quelqu’un",
    "Je n’ai jamais chahuté un spectacle en direct",
    "Je n’ai jamais subi de chirurgie",
    "Je n’ai jamais heurté une voiture en stationnement",
    "Je n’ai jamais organisé une fête surprise pour quelqu’un d’autre",
    "Je n’ai jamais eu de fête surprise organisée pour moi",
    "Je n’ai jamais porté de perruque ou d’extensions",
    "Je ne me suis jamais habillé en drag queen",
    "Je n’ai jamais fouillé dans les poubelles",
    "Je n’ai jamais rendu quelque chose après l’avoir porté",
    "Je n’ai jamais fait pipi dans mon pantalon à l’âge adulte",
    "Je n’ai jamais été dans un hélicoptère",
    "Je n’ai jamais perdu mes chaussures pendant une soirée",
    "Je ne me suis jamais garé sur une place pour handicapés",
    "Je n’ai jamais flirté avec une personne mariée",
    "Je n’ai jamais remis en question une relation",
    "Je n’ai jamais eu d’appareil dentaire",
    "Je n’ai jamais eu de carie",
    "Je n’ai jamais fait d’auto-stop",
    "Je n’ai jamais pris un auto-stoppeur",
    "Je n’ai jamais changé un pneu",
    "Je n’ai jamais menti sur mon statut relationnel",
    "Je n’ai jamais menti sur un profil de rencontre",
    "Je n’ai jamais eu le mal de mer",
    "Je n’ai jamais eu le cœur brisé",
    "Je n’ai jamais brisé le cœur de quelqu’un d’autre",
    "Je n’ai jamais eu le coup de foudre",
    "Je n’ai jamais éternué sur un étranger",
    "Je n’ai jamais vomi en public",
    "Je n’ai jamais souhaité avoir des enfants",
    "Je n’ai jamais souhaité ne pas avoir d’enfants",
    "Je n’ai jamais vu quelque chose d’effrayant dans les transports en commun",
    "Je n’ai jamais envoyé de sexto à un ex",
    "Je n’ai jamais envoyé un sexto à la mauvaise personne",
    "Je n’ai jamais mis de chewing-gum dans mes cheveux",
    "Je n’ai jamais surpris mes parents en train de le faire",
    "Je n’ai jamais mangé un paquet entier d’Oreos en une seule fois",
    "Je n’ai jamais bu une bouteille de vin entière",
    "Je n’ai jamais été témoin d’un crime",
    "Je ne suis jamais monté à cheval",
    "Je ne me suis jamais évanoui(e)",
    "Je n’ai jamais bouché les toilettes",
    "Je n’ai jamais fait de camping",
    "Je n’ai jamais donné mon sang",
    "Je ne me suis jamais battu physiquement",
    "Je n’ai jamais surveillé l’ex de mon partenaire sur les réseaux sociaux",
    "Je n’ai jamais filmé un moment intime",
    "Je n’ai jamais tiré avec une arme à feux",
    "Je n’ai jamais fait tomber un bébé",
    "Je n’ai jamais couru un marathon",
    "Je n’ai jamais menti sur la personne pour laquelle j’ai voté",
    "Je n’ai jamais partagé une nouvelle sans lire au-delà du titre",
    "Je n’ai jamais été licencié d’un emploi",
    "Je ne me suis jamais disputé avec un partenaire en public",
    "Je n’ai jamais battu un jeu vidéo",
    "Je n’ai jamais flirté avec un serveur ou un barman",
    "Je n’ai jamais été serveur de tables",
    "Je n’ai jamais travaillé dans le commerce de détail",
    "Je n’ai jamais brûlé un feu rouge",
    "Je n’ai jamais été trompé(e)",
    "Je n’ai jamais fait l’objet d’une rumeur qui n’était pas vraie",
    "Je n’ai jamais répandu une rumeur que je savais fausse",
    "Je n’ai jamais rencontré une célébrité",
    "Je n’ai jamais donné moins de % de pourboire",
    "Je n’ai jamais donné plus de % de pourboire",
    "Je n’ai jamais pleuré à une fête",
    "Je n’ai jamais pleuré au travail",
    "Je n’ai jamais pleuré en public",
    "Je n’ai jamais utilisé les toilettes d’une station-service",
    "Je ne suis jamais allé(e) au travail avec la gueule de bois",
    "Je n’ai jamais juré devant un beau-parent",
    "Je n’ai jamais juré contre un membre de ma belle-famille",
    "Je ne me suis jamais produit sur scène",
    "Je n’ai jamais ri à un enterrement",
    "Je n’ai jamais donné à quelqu’un un faux numéro de téléphone",
    "Je n’ai jamais laissé un commentaire méchant sur YouTube",
    "Je ne suis jamais monté dans une voiture de police",
    "Je n’ai jamais fait de croisière",
    "Je n’ai jamais visité une plage nudiste",
    "Je n’ai jamais juré devant un enfant",
    "Je n’ai jamais appelé les flics pour quelqu’un d’autre",
    "Je n’ai jamais volé à l’étalage",
    "Je n’ai jamais fait de saut à l’élastique",
    "Je n’ai jamais passé plus de trois jours sans me doucher",
    "Je n’ai jamais passé plus d’un jour sans me brosser les dents",
    "Je n’ai jamais été « ghosté » par quelqu’un",
    "Je n’ai jamais reproché à quelqu’un d’autre une erreur au travail",
    "Je ne me suis jamais attribué le mérite du travail de quelqu’un d’autre"
];

var languages = keys(questions);
var language = (navigator.userLanguage || navigator.language).slice(0, 2);
var clanguage = ('; '+document.cookie).split(`; LANG=`).pop().split(';')[0];
if(languages.includes(clanguage)){
	language = clanguage;
}
function switchLang(lang){
	document.cookie = "LANG="+lang+"; expires="+new Date(Date.now()+315360000000).toUTCString()+ ";path=/";
	location.reload();
}
var questionsEx = languages.reduce((a,v) => ({ ...a, [v]: []}), {});
//used to show a prefix title to the question, also filters out these words from the question
var nhie = {
	en : "Never have I ever",
	cs : "Nikdy jsem",
	pt : "Eu nunca"
}

function pickQuestion(){
	const excludeMap = questionsEx[language].reduce((all, item) => ({ ...all, [item]: true }), {});
	const uniqueQuestions = questions[language].filter((item) => !excludeMap?.[item]);
	var rand =  Math.floor(Math.random() * (uniqueQuestions.length - 1));
	window.questionsEx[language].push(uniqueQuestions[rand]);
	return [rand, uniqueQuestions[rand].split(nhie[language], 3)[1].trim()];
}
var players = {};
function addPlayer(name){
	window.players[name] = {
		questions : []
	};
}
function addPlayers(playerList){
	playerList.forEach((name) => {
		addPlayer(name);
	});
}
//call this when drawing a new question so we can keep track of who drank. Question is an ID of the question
function addScore(playerList, question){
	playerList.forEach((name) => {
		window.players[name].questions.push(question);
	});
}
function genScoreboard(){
	return Object.entries(window.players).sort(function(a,b){
		return b[1].questions.length-a[1].questions.length;
	});
}
