var questions = {};
questions.cs = [
    "Nikdy jsem nebyl(a) omylem zastaven(a) policií.",
    "Nikdy jsem sněhulákovi neudělal(a) prsa s pinďourem.",
    "Nikdy jsem nezažil(a), že by mi v práci proplatili celý den, aniž bych musel(a) hnout prstem.",
    "Nikdy jsem nebyl(a) náměsíčný/á.",
    "Nikdy jsem nepřistihl(a) své rodiče při sexu.",
    "Nikdy jsem si do čaje nedal(a) místo cukru sůl.",
    "Nikdy jsem neměl(a) nic zlomeného.",
    "Nikdy jsem neměl(a) rád(a), nebo nepil(a) rajčatový džus.",
    "Nikdy jsem omylem hlavou nerozbil(a) lustr.",
    "Nikdy jsem neomdlel(a).",
    "Nikdy jsem neposiloval(a).",
    "Nikdy jsem na sobě neměl(a) pyžamo.",
    "Nikdy jsem nic nesbíral(a) (např. známky).",
    "Nikdy jsem si nepodal(a) ruku s celebritou.",
    "Nikdy jsem nezažil(a), že by mě ve spánku pozvracel pes.",
    "Nikdy jsem neulovil(a) živou rybu.",
    "Nikdy jsem si nevyrazil(a) dech.",
    "Nikdy jsem netoužil(a) po sexu s nějakou celebritou.",
    "Nikdy jsem neviděl(a) živou světlušku.",
    "Nikdy jsem neviděl(a) ducha, ani nezažil(a) nic jiného, nadpřirozeného.",
    "Nikdy jsem v životě nemusel(a) bojovat o život.",
    "Nikdy jsem se nenaučil(a) lyžovat.",
    "Nikdy jsem nebyl(a) na Slovensku.",
    "Nikdy jsem si nepřivřel(a) prst do dveří.",
    "Nikdy jsem nevyrazil(a) na nákup omylem bez peněz.",
    "Nikdy jsem nevykouřil(a) víc jak 3 cigarety denně.",
    "Nikdy jsem omylem nesnědl(a) mouchu.",
    "Nikdy jsem nebyl(a) vzrušený/á z toho, když někdo okolo mě měl sex.",
    "Nikdy jsem po silnici (mimo dálnici) nejel(a) víc jak 100 km/hod.",
    "Nikdy jsem nechodil(a) po bytě v botech od bláta.",
    "Nikdy jsem se jen tak nepodíval(a) na porno.",
    "Nikdy jsem na vysvědčení neměl(a) horší známku než trojku.",
    "Nikdy jsem nejedl(a) žádné zvíře zaživa.",
    "Nikdy jsem nikomu nic neudělal(a) ve spánku (např. pomalování obličeje).",
    "Nikdy jsem nezažil(a) jídlo při svíčkách.",
    "Nikdy jsem na nikoho nenalíčil(a) past.",
    "Nikdy jsem si nezkazil(a) účes tím, že jsem se vlastoručně ostříhal(a).",
    "Nikdy jsem se na veřejnosti nekoupal(a) mezi lidmi nahý/á (mimo dětství).",
    "Nikdy jsem minimálně do pěti let nevěděl(a) o tom, že existuje sex.",
    "Nikdy jsem nebyl(a) vzhůru déle než 48 hodin.",
    "Nikdy jsem nedokázal(a) nejíst víc jak 24 hodin.",
    "Nikdy jsem si ilegálně nestáhl(a) nějakou věc.",
    "Nikdy jsem si v životě nerozbil(a) víc jak 2 mobily.",
    "Nikdy jsem nevyhodil(a) svůj mobil do dáli a totálně ho nerozsekal(a).",
    "Nikdy jsem nezjistil(a), jak obratně nakrájet cibuli na kostičky.",
    "Nikdy jsem se se svým/svou dosavadní nejlepší kamarádkou/kamarádem nepohádal(a).",
    "Nikdy jsem neudělal(a) to, že bych nalezenou peněženku nevrátil(a), nebo nenahlásil(a).",
    "Nikdy jsem se nesnažil(a) někoho opít.",
    "Nikdy jsem neměl(a) kamaráda/kamarádku, co by jeli na drogách (těžších než marihuana).",
    "Nikdy jsem nešmíroval(a) někoho nahého pod vodou.",
    "Nikdy jsem si nechatoval(a) s jinými lidmi během sexu.",
    "Nikdy jsem neměl(a) pohlavní nemoc.",
    "Nikdy jsem neprojížděl(a) svému nejlepšímu kamarádovi/kamarádce mobil (aniž by o tom věděl(a)).",
    "Nikdy jsem úmyslně nesnědl(a) nic zkaženého.",
    "Nikdy jsem nebyl(a) na rande s více jak jedním člověkem.",
    "Nikdy jsem se neopil(a) do bezvědomí.",
    "Nikdy jsem si nic nekupoval(a) v sexshopu.",
    "Nikdy jsem se nechlubil(a), že jsem měl(a) sex s někým, když to nebyla pravda.",
    "Nikdy jsem nezažil(a), že by mi někdo nabídl, že by se mnou chtěl mít sex (počítá se i partner).",
    "Nikdy jsem se po 12. roce života nevyčůral(a) do bazénu.",
    "Nikdy jsem nezkoušel(a) tvrdší drogy, než je tráva.",
    "Nikdy jsem si nevolal(a) s někým během sexu.",
    "Nikdy jsem z legrace fyzicky neubližoval(a) zvířatům.",
    "Nikdy jsem nic naschvál v práci nerozbil(a).",
    "Nikdy jsem nepodvedl(a) svou polovičku.",
    "Nikdy jsem nikomu nezůstal(a) dlužníkem peněz.",
    "Nikdy jsem se na internetu nevydával(a) za někoho jiného.",
    "Nikdy jsem si během sprchování nepořizoval(a) selfie.",
    "Nikdy jsem neměl(a) víc jak 10 sexuálních partnerů.",
    "Nikdy jsem nepoužíval(a) vlastoručně vyráběnou, erotickou hračku.",
    "Nikdy jsem nepředstíral(a), že se s kamarády dobře bavím a potom je druhý den nepomlouval(a).",
    "Nikdy jsem před jiným člověkem ze srandy neponížil(a) svého nejlepšího kamaráda/kamarádku.",
    "Nikdy jsem se s dítětem nekoukal(a) na nic erotického.",
    "Nikdy jsem nezvracel(a) ožralý/á ve spánku.",
    "Nikdy jsem sexuálně nezneužil(a) partnera, zatímco spal.",
    "Nikdy jsem si nefotil(a) svoje přirození.",
    "Nikdy jsem nespal(a) s nikým pod 13 let.",
    "Nikdy jsem nikomu neukradl(a) peníze.",
    "Nikdy jsem nikomu neplivl(a) do jídla.",
    "Nikdy jsem nedal(a) živého tvora do mikrovlnky a tím nezabil(a).",
    "Nikdy jsem svému nejlepšímu kamarádovi nepřebral(a) partnera.",
    "Nikdy jsem nebyl(a) sprostý/á na svoje rodiče.",
    "Nikdy jsem za zády nepomlouval(a) svého nejlepšího kamaráda/kamarádku, i když jsem se před ním tvářil(a), že je vše v pořádku.",
    "Nikdy jsem nikomu neřekl(a), že spousta mých vztahů byl(a) jen kvůli tomu, abych nebyl(a) v životě bez partnera.",
    "Nikdy jsem na nikoho úspěšně nehodil(a) svůj velký prohřešek.",
    "Nikdy jsem naschvál malému dítěti nedal(a) něco odporného k jídlu, co normální lidi nejedí (např. hmyz).",
    "Nikdy jsem nepomyslel(a) na to, že bych zahnul(a) své dosavadní polovičce.",
    "Nikdy jsem neměl(a) sex s člověkem, který nevěděl, že trpím pohlavní nemocí.",
    "Nikdy jsem nebyl(a) na testu proti HIV i když jsem měl(a) více jak 15 sexuálních partnerů.",
    "Nikdy jsem nikomu neřekl(a) o pravdě, že mě sexuálně přitahuje stejné pohlaví.",
    "Nikdy jsem nikomu neřekl(a), že bych nechtěl(a) mít děti i když je to pravda.",
    "Nikdy jsem neměl(a) v úmyslu dát peníze na charitu i když bych měl(a) na účtě více jak 100 milionů korun.",
    "Nikdy jsem nikomu neřekl(a), že nemám moc kamarádské pouto se svými rodiči, i když je to pravda.",
    "Nikdy jsem s někým nespal(a) jen kvůli tomu, abych zahnal(a) svoje sexuální choutky, i když si o mně dotyčný myslel něco jiného.",
    "Nikdy jsem nikomu neřekl(a) &#8220;miluji tě&#8221;.",
    "Nikdy jsem se v dospělosti nerozbrečel(a) u doktora.",
    "Nikdy jsem nedokázal(a) všem svým nejbližším říct, že mám nějaké fyzické postižení.",
    "Nikdy jsem nepomyslel(a) na to, že bych chtěl(a), aby někdo z mé rodiny zemřel, abych měl(a) nárok na nemovitost.",
    "Nikdy jsem nešířil(a) největší tajemství toho, kdo mi věřil.",
    "Nikdy jsem v análu neměl(a) žádnou erotickou pomůcku.",
    "Nikdy jsem se na záchodě neutřela ruličkou od papíru.",
    "Nikdy jsem nepředváděla nějaký klip když jsem byl/a sama doma.",
    "Nikdy jsem nehodil odpadek do trávy.",
    "Nikdy jsem neměl pohlavní styk.",
    "Nikdy jsem si nečistil zuby prstem.",
    "Nikdy jsem neukradl peníze.",
    "Nikdy jsem nešáhl opačému pohlaví za zadek.",
    "Nikdy jsem se nechtěl vyspat s youtuberem.",
    "Nikdy jsem neřekl sprosté slovo před učitelem.",
    "Nikdy jsem kamarádovi nepoblil boty (xD).",
    "Nikdy jsem nedal opačnému pohlaví facku.",
    "Nikdy jsem neběhal nahý po domě, bytě.",
    "Nikdy jsem neukradl něco na návštěvě.",
    "Nikdy jsem nezkoušel odemknout mobil jazykem.",
    "Nikdy jsem si pořádně nahlas neprdl na veřejnosti.",
    "Nikdy jsem se nepozvracel na silvestra.",
    "Nikdy jsem neviděl youtubera.",
    "Nikdy jsem nenadával na oblíbeného youtubera.",
    "Nikdy jsem neměl nejvíc likeovaný komentář u videa.",
    "Nikdy jsem netočil video na youtube.",
    "Nikdy jsem neměl děsnou chut na něco co nemám rád.",
    "Nikdy jsem neusnul u filmu.",
    "Nikdy jsem nechtěl utéct z domu.",
    "Nikdy jsem nezkoušel helium.",
    "Nikdy jsem se nepohádal v obchodě se zaměstanavatelem. (hlídačkou,prodavačkou)",
    "Nikdy jsem neměl myšlenku o tom že se zabiju.",
    "Nikdy jsem se nepočural smíchy.",
    "Nikdy jsem neměl pindíka. (xD)",
    "Nikdy jsem se nevyčural do vany nebo do sprchy.",
    "Nikdy jsem si nedával nohy za hlavu.",
    "Nikdy jsem si nečuchl k mému prdu.",
    "Nikdy jsem nedal dislike Gogovy.",
    "Nikdy jsem na sobě neměl make-up.",
    "Nikdy jsem neutopil rybu.",
    "Nikdy jsem se pořádně nevykakal.",
    "Nikdy jsem nebyl v kině na hororu.",
    "Nikdy jsem se nevysmrkal do ponošky.",
    "Nikdy jsem nedělal balonky z kondomů..",
    "Nikdy jsem nepromluvil rasisticky.",
    "Nikdy jsem neurážel Miloše Zemana.",
    "Nikdy jsem nekouřil.",
    "Nikdy jsem se nelíbal se stejným pohlavím.",
    "Nikdy jsem se nelíbal se spolužákem.",
    "Nikdy jsem nehrál Minecraft.",
    "Nikdy jsem neměla záchvat smíchu z videií FattyhoPillowa.",
    "Nikdy jsem nezpíval song od Mishovy Šílenosti.",
    "Nikdy jsem nikomu nedal přes držku.",
    "Nikdy jsem nedostal přes držku."
];
questions.en = [
    "Never have I ever gone skinny dipping.",
    "Never have I ever gone on a blind date.",
    "Never have I ever creeped an ex on social media.",
    "Never have I ever been hungover.",
    "Never have I ever kissed my best friend.",
    "Never have I ever ghosted someone.",
    "Never have I ever gotten a speeding ticket.",
    "Never have I ever slid into someone's DMs.",
    "Never have I ever dined and dashed.",
    "Never have I ever used a fake ID.",
    "Never have I ever had a crush on a teacher.",
    "Never have I ever been in love.",
    "Never have I ever made out in a public place.",
    "Never have I ever gotten into a physical fight.",
    "Never have I ever had an alcoholic drink.",
    "Never have I ever played spin the bottle.",
    "Never have I ever snooped through someone's phone.",
    "Never have I ever snuck into a movie theater.",
    "Never have I ever kissed a friend's ex.",
    "Never have I ever told someone \"I love you\" without meaning it.",
    "Never have I ever been called a player.",
    "Never have I ever smoked a cigarette.",
    "Never have I ever given a lap dance.",
    "Never have I ever gotten a lap dance.",
    "Never have I ever cheated on a test.",
    "Never have I ever used a dating app.",
    "Never have I ever kissed more than one person in hours.",
    "Never have I ever cheated on someone.",
    "Never have I ever been cheated on.",
    "Never have I ever sent a racy text to the wrong person.",
    "Never have I ever had a negative bank account balance.",
    "Never have I ever played strip poker.",
    "Never have I ever been arrested.",
    "Never have I ever been expelled.",
    "Never have I ever stolen anything.",
    "Never have I ever gotten a hickey.",
    "Never have I ever been fired.",
    "Never have I ever made out in a movie theater.",
    "Never have I ever dated someone older than me.",
    "Never have I ever dated someone younger than me.",
    "Never have I ever broken the law.",
    "Never have I ever been to a nude beach.",
    "Never have I ever stood a date up.",
    "Never have I ever stayed in a relationship that I really wasn’t feeling.",
    "Never have I ever given someone a fake phone number.",
    "Never have I ever lied to someone in this room.",
    "Never have I ever broken up with someone over text.",
    "Never have I ever had a crush on an SO’s best friend.",
    "Never have I ever shoplifted.",
    "Never have I ever seen a ghost.",
    "Never have I ever told a secret I wasn’t supposed to share.",
    "Never have I ever had a friend with benefits.",
    "Never have I ever intentionally started a fight between other people.",
    "Never have I ever dated more than one person at once.",
    "Never have I ever spent money that wasn’t mine to spend.",
    "Never have I ever had a relationship last less than a month.",
    "Never have I ever had a relationship last longer than a year.",
    "Never have I ever gotten an unexpected piercing.",
    "Never have I ever found a dumb excuse to text an ex.",
    "Never have I ever fallen in love at first sight.",
    "Never have I ever kissed someone I just met.",
    "Never have I ever kept a crush secret from people in this room.",
    "Never have I ever been in love with someone without them knowing.",
    "Never have I ever been in an open relationship.",
    "Never have I ever fantasized about getting back with an ex.",
    "Never have I ever helped a friend lie by being their alibi.",
    "Never have I ever seriously thought about marrying someone.",
    "Never have I ever had a totally online relationship.",
    "Never have I ever flirted just to get something I wanted.",
    "Never have I ever tried guessing someone’s password.",
    "Never have I ever been caught lying.",
    "Never have I ever farted in front of a significant other.",
    "Never have I ever peed in the shower.",
    "Never have I ever peed in a pool.",
    "Never have I ever eaten a carton of ice cream.",
    "Never have I ever cheated in a board game.",
    "Never have I ever cheated in a card game.",
    "Never have I ever screamed during a scary movie.",
    "Never have I ever laughed so hard I spit out my drink.",
    "Never have I ever been sent to the principal's office.",
    "Never have I ever clogged a toilet.",
    "Never have I ever toilet-papered someone's house.",
    "Never have I ever worn something I took out of my dirty laundry.",
    "Never have I ever vomited after a roller coaster ride.",
    "Never have I ever watched an entire television series in a day.",
    "Never have I ever said “I love you” to someone by accident.",
    "Never have I ever walked in on my parents having sex.",
    "Never have I ever lied while playing this game.",
    "Never have I ever Googled myself.",
    "Never have I ever had a pet name for an SO.",
    "Never have I ever been given a pet name by an SO.",
    "Never have I ever had a dirty dream about a super unexpected person.",
    "Never have I ever been accused of sharing too much on social media.",
    "Never have I ever created a fake social media account.",
    "Never have I ever run out of gas while driving.",
    "Never have I ever gone to a party I wasn’t invited to.",
    "Never have I ever dated someone super annoying only because they’re cute.",
    "Never have I ever lied on a first date.",
    "Never have I ever used someone else's toothbrush.",
    "Never have I ever pretended to be on the phone.",
    "Never have I ever enjoyed a smell I’m supposed to find gross.",
    "Never have I ever been on TV for an embarrassing reason.",
    "Never have I ever gone several days without showering.",
    "Never have I ever turned my underwear inside out so I don’t have to wash it.",
    "Never have I ever lied about what I was doing on social media.",
    "Never have I ever been told I snore loudly.",
    "Never have I ever had a crush on a friend's sibling.",
    "Never have I ever gone commando.",
    "Never have I ever shaved my head.",
    "Never have I ever gotten a tattoo.",
    "Never have I ever broken a bone.",
    "Never have I ever been to a bachelorette party or bachelor party.",
    "Never have I ever gotten heated during a family game night.",
    "Never have I ever met a celebrity.",
    "Never have I ever had a surprise party thrown for me.",
    "Never have I ever travelled solo.",
    "Never have I ever eaten whipped cream straight out of the can.",
    "Never have I ever auditioned for a reality television show.",
    "Never have I ever told my parents I was staying at a friend's house but was really somewhere else.",
    "Never have I ever been to a psychic.",
    "Never have I ever lived alone.",
    "Never have I ever sang karaoke.",
    "Never have I ever stayed overnight in the hospital.",
    "Never have I ever deleted a post because it didn't get enough likes.",
    "Never have I ever stayed up all night.",
    "Never have I ever been on a cruise.",
    "Never have I ever lost a bet.",
    "Never have I ever gotten in a car accident.",
    "Never have I ever rode a motorcycle.",
    "Never have I ever pretended to be sick to get out of school.",
    "Never have I ever beaten a video game.",
    "Never have I ever cried at school.",
    "Never have I ever talked to a family member about my sex life.",
    "Never have I ever been to Mexico.",
    "Never have I ever eaten caviar.",
    "Never have I ever used someone else's Netflix password.",
    "Never have I ever fallen asleep in class.",
    "Never have I ever dyed my hair.",
    "Never have I ever read an entire book in a day.",
    "Never have I ever seen an alligator in real life.",
    "Never have I ever re-gifted a gift.",
    "Never have I ever sleepwalked.",
    "Never have I ever gone snowboarding.",
    "Never have I ever been awake for hours (or more) straight.",
    "Never have I ever broken up with someone in a way I regret.",
    "Never have I ever fainted.",
    "Never have I ever had a fight with a SO in public.",
    "Never have I ever knowingly spread a rumor.",
    "Never have I ever been somewhere I was sure was haunted.",
    "Never have I ever cut my own hair.",
    "Never have I ever lied to get out of plans with friends.",
    "Never have I ever cheated on a partner.",
    "Never have I ever faked sick from work.",
    "Never have I ever marched in a protest.",
    "Never have I ever overdrafted my bank account.",
    "Never have I ever eaten someone else’s lunch from the office fridge.",
    "Never have I ever smoked a joint.",
    "Never have I ever tried hard drugs.",
    "Never have I ever fallen asleep in public.",
    "Never have I ever fallen asleep at work.",
    "Never have I ever lied on my resume.",
    "Never have I ever drunk-dialed my ex.",
    "Never have I ever dropped acid.",
    "Never have I ever had a one-night stand.",
    "Never have I ever read a partner’s text messages.",
    "Never have I ever read a partner’s emails.",
    "Never have I ever been hospitalized for something other than giving birth or being born.",
    "Never have I ever sang in public.",
    "Never have I ever played a musical instrument.",
    "Never have I ever gone skiing.",
    "Never have I ever traveled to a foreign country.",
    "Never have I ever learned a foreign language.",
    "Never have I ever sent a stranger a drink.",
    "Never have I ever accepted a drink from a stranger.",
    "Never have I ever lied about my income.",
    "Never have I ever gotten busy in a public place.",
    "Never have I ever been nude in public.",
    "Never have I ever dated or hooked up with someone years older.",
    "Never have I ever dated or hooked up with someone 5 years younger.",
    "Never have I ever texted or taken a call at the movies.",
    "Never have I ever convinced a friend to dump a partner.",
    "Never have I ever convinced a partner to dump a friend.",
    "Never have I ever been someone else’s alibi.",
    "Never have I ever hopped a turnstile.",
    "Never have I ever snitched on someone else at work.",
    "Never have I ever donated an organ.",
    "Never have I ever lied to a law enforcement officer.",
    "Never have I ever been a maid of honor.",
    "Never have I ever been a best man.",
    "Never have I ever called a partner the wrong name.",
    "Never have I ever thought a friend’s baby was ugly.",
    "Never have I ever won more than $gambling.",
    "Never have I ever lost more than $gambling.",
    "Never have I ever gone vegan.",
    "Never have I ever lied about my age.",
    "Never have I ever had a lucid dream.",
    "Never have I ever campaigned for a political candidate.",
    "Never have I ever had chicken pox.",
    "Never have I ever flashed someone.",
    "Never have I ever mooned someone.",
    "Never have I ever lied to my best friend.",
    "Never have I ever had a road rage incident.",
    "Never have I ever cut in line on purpose.",
    "Never have I ever held a grudge longer than a year.",
    "Never have I ever blabbed something I swore to secrecy.",
    "Never have I ever ruined someone else’s vacation.",
    "Never have I ever chipped a tooth.",
    "Never have I ever tried a fad diet.",
    "Never have I ever been awake for straight hours or more.",
    "Never have I ever accidentally said “I love you” to someone.",
    "Never have I ever cried or flirted my way out of a ticket.",
    "Never have I ever snooped through a friend’s room, cabinets or property.",
    "Never have I ever gotten busy in a car.",
    "Never have I ever worked with someone I couldn’t stand.",
    "Never have I ever eaten food that broke the five-second rule.",
    "Never have I ever spent an entire day watching reality TV.",
    "Never have I ever sent nudes.",
    "Never have I ever received nudes.",
    "Never have I ever blamed a fart on a pet.",
    "Never have I ever thought a cartoon character was hot.",
    "Never have I ever Googled someone before a date.",
    "Never have I ever re-gifted something.",
    "Never have I ever crashed a party or wedding.",
    "Never have I ever dated a musician.",
    "Never have I ever been on a blind date.",
    "Never have I ever gotten or given a hickey.",
    "Never have I ever gotten a bedroom-related injury.",
    "Never have I ever tried moonshine.",
    "Never have I ever seen someone die.",
    "Never have I ever had a wardrobe malfunction.",
    "Never have I ever run for my life.",
    "Never have I ever been in a talent show.",
    "Never have I ever gotten stitches.",
    "Never have I ever tried to make an ex jealous.",
    "Never have I ever driven a stick shift.",
    "Never have I ever set something on fire while cooking.",
    "Never have I ever set a friend up on a date.",
    "Never have I ever started a hashtag.",
    "Never have I ever paid for adult content.",
    "Never have I ever been scuba diving.",
    "Never have I ever hooked up with someone of the same sex or gender.",
    "Never have I ever done a “drive-by” of an ex or crush’s house.",
    "Never have I ever danced in the rain.",
    "Never have I ever danced on a table.",
    "Never have I ever joined the mile-high club.",
    "Never have I ever slept in my car.",
    "Never have I ever been on TV.",
    "Never have I ever had frostbite.",
    "Never have I ever had a blistering sunburn.",
    "Never have I ever gotten sick on a date.",
    "Never have I ever had food poisoning.",
    "Never have I ever purposely given someone bad advice.",
    "Never have I ever heckled a live performance.",
    "Never have I ever had surgery.",
    "Never have I ever hit a parked car.",
    "Never have I ever thrown someone else a surprise party.",
    "Never have I ever adjusted myself in public.",
    "Never have I ever worn a wig or extensions.",
    "Never have I ever dressed in drag.",
    "Never have I ever been dumpster diving.",
    "Never have I ever returned something after I wore it.",
    "Never have I ever peed my pants as an adult.",
    "Never have I ever slid into a stranger’s DMs.",
    "Never have I ever slid into an ex’s DMs.",
    "Never have I ever been in a helicopter.",
    "Never have I ever lost my shoes during a night out.",
    "Never have I ever parked in a handicap spot.",
    "Never have I ever flirted with a married person.",
    "Never have I ever second-guessed a relationship.",
    "Never have I ever had braces.",
    "Never have I ever had a cavity.",
    "Never have I ever hitchhiked.",
    "Never have I ever picked up a hitchhiker.",
    "Never have I ever changed a tire.",
    "Never have I ever lied about my relationship status.",
    "Never have I ever lied on a dating profile.",
    "Never have I ever gotten seasick.",
    "Never have I ever had a broken heart.",
    "Never have I ever broken someone else’s heart.",
    "Never have I ever fallen in love.",
    "Never have I ever sneezed on a stranger.",
    "Never have I ever thrown up in public.",
    "Never have I ever wished I had kids.",
    "Never have I ever wished I didn’t have kids.",
    "Never have I ever seen something creepy while using public transportation.",
    "Never have I ever sexted an ex.",
    "Never have I ever sent a sext to the wrong person.",
    "Never have I ever gotten gum in my hair.",
    "Never have I ever walked in on my parents.",
    "Never have I ever eaten an entire pizza alone.",
    "Never have I ever eaten an entire pack of Oreos in one sitting.",
    "Never have I ever drank an entire bottle of wine.",
    "Never have I ever witnessed a crime.",
    "Never have I ever ridden a horse.",
    "Never have I ever been camping.",
    "Never have I ever donated blood.",
    "Never have I ever gotten in a physical fight.",
    "Never have I ever lurked my partner’s ex on social media.",
    "Never have I ever snuck into a movie.",
    "Never have I ever filmed an intimate moment.",
    "Never have I ever fired a gun.",
    "Never have I ever dropped a baby.",
    "Never have I ever run a marathon.",
    "Never have I ever lied about who I voted for.",
    "Never have I ever shared a news story without reading past the headline.",
    "Never have I ever been fired from a job.",
    "Never have I ever fought with a partner in public.",
    "Never have I ever flirted with a waiter or bartender.",
    "Never have I ever waited tables.",
    "Never have I ever worked retail.",
    "Never have I ever been blackout drunk.",
    "Never have I ever run a red light.",
    "Never have I ever been the subject of a rumor that wasn’t true.",
    "Never have I ever spread a rumor I knew wasn’t true.",
    "Never have I ever tipped less than percent.",
    "Never have I ever tipped more than percent.",
    "Never have I ever cried at a party.",
    "Never have I ever cried at work.",
    "Never have I ever cried in public.",
    "Never have I ever used a gas station bathroom.",
    "Never have I ever gotten into a fender bender.",
    "Never have I ever gone to work hungover.",
    "Never have I ever cursed in front of an in-law.",
    "Never have I ever cursed at an in-law.",
    "Never have I ever worn white to a wedding.",
    "Never have I ever performed onstage.",
    "Never have I ever laughed at a funeral.",
    "Never have I ever left a mean YouTube comment.",
    "Never have I ever trolled a stranger online.",
    "Never have I ever been in a police car.",
    "Never have I ever danced on a pole.",
    "Never have I ever been to a strip club.",
    "Never have I ever watched a NASCAR race.",
    "Never have I ever been to a pro wrestling match.",
    "Never have I ever been to an MLB  game.",
    "Never have I ever been to an NBA or WNBA game.",
    "Never have I ever been to an NFL game.",
    "Never have I ever been to an NHL game.",
    "Never have I ever gone surfing.",
    "Never have I ever tried bodybuilding.",
    "Never have I ever tried cross-fit.",
    "Never have I ever visited a nude beach.",
    "Never have I ever cursed in front a of a child.",
    "Never have I ever called the cops on someone else.",
    "Never have I ever gone bungee jumping.",
    "Never have I ever left a negative Yelp review.",
    "Never have I ever went more than three days without showering.",
    "Never have I ever went more than a day without brushing my teeth.",
    "Never have I ever read someone else’s mail.",
    "Never have I ever been ghosted.",
    "Never have I ever blamed someone else for my mistake at work.",
    "Never have I ever taken credit for someone else’s work.",
    "Never have I ever hooked up with a friend’s sibling.",
    "Never have I ever hooked up with a sibling’s friend.",
    "Never have I ever hooked up with a friend’s ex.",
    "Never have I ever hooked up with an ex’s friend.",
    "Never have I ever had a black eye.",
    "Never have I ever lost my voice.",
    "Never have I ever given a eulogy.",
    "Never have I ever stolen something from my workplace.",
    "Never have I ever stagedived.",
    "Never have I ever been backstage at a concert.",
    "Never have I ever been someone’s one phone call from jail.",
    "Never have I ever lied to my kids.",
    "Never have I ever lied to my parents.",
    "Never have I ever gone more than mph over the speed limit.",
    "Never have I ever had a paranormal experience.",
    "Never have I ever gone skydiving.",
    "Never have I ever spent a night in jail.",
    "Never have I ever dined and ditched.",
    "Never have I ever lurked my ex on social media.",
    "Never have I ever lied on social media.",
    "Never have I ever eaten a ghost pepper.",
    "Never have I ever auditioned for a reality show.",
    "Never have I ever kissed a stranger.",
    "Never have I ever prank called someone.",
    "Never have I ever gone streaking.",
    "Never have I ever lied during this game!"
];
questions.pt = [
    "Eu nunca fiquei obcecado em stalkear alguém nas redes sociais.",
    "Eu nunca fui expulso da sala de aula.",
    "Eu nunca desmaiei na rua.",
    "Eu nunca fui parado por policiais.",
    "Eu nunca quebrei um osso.",
    "Eu nunca quebrei um dente.",
    "Eu nunca criei uma conta falsa nas redes sociais.",
    "Eu nunca tive uma experiência paranormal.",
    "Eu nunca tive algum perfil de rede social hackeado.",
    "Eu nunca tive paralisia do sono.",
    "Eu nunca fiquei preso no elevador.",
    "Eu nunca tentei cortar meu próprio cabelo.",
    "Eu nunca pintei o cabelo de alguma cor estranha.",
    "Eu nunca apareci na TV.",
    "Eu nunca passei mal em um parque de diversões.",
    "Eu nunca corri da polícia.",
    "Eu nunca pedi dinheiro no sinal.",
    "Eu nunca me arrependi imediatamente após enviar uma mensagem.",
    "Eu nunca levei um tapa no rosto.",
    "Eu nunca dei um tapa no rosto de alguém.",
    "Eu nunca participei de uma briga.",
    "Eu nunca chorei no transporte público.",
    "Eu nunca passei mais de dois dias sem tomar banho.",
    "Eu nunca olhei o celular de alguém sem que a pessoa soubesse.",
    "Eu nunca fui demitido.",
    "Eu nunca dormi na rua.",
    "Eu nunca consegui algo de graça dando em cima de alguém.",
    "Eu nunca tive um vídeo constrangedor postado na internet.",
    "Eu nunca quebrei algo na casa de alguém e escondi.",
    "Eu nunca saí de uma festa ou bar sem pagar.",
    "Eu nunca me gabei por algo que não fiz.",
    "Eu nunca menti tanto sobre algo que acreditei que fosse verdade.",
    "Eu nunca sofri bullying na escola.",
    "Eu nunca segurei a mão da pessoa errada na rua.",
    "Eu nunca fui expulso de uma festa.",
    "Eu nunca postei algo e me arrependi.",
    "Eu nunca roubei dinheiro da carteira dos meus pais.",
    "Eu nunca comi comida que caiu no chão.",
    "Eu nunca comi comida que alguém largou na área de alimentação do shopping.",
    "Eu nunca fiquei com o irmão/irmã de um amigo.",
    "Eu nunca dormi no ônibus e perdi o meu ponto.",
    "Eu nunca fiquei apaixonado por algum professor.",
    "Eu nunca fui assaltado.",
    "Eu nunca recebi flores.",
    "Eu nunca menti para meus pais sobre onde estava indo.",
    "Eu nunca fiz xixi em uma piscina do lado dos meus amigos.",
    "Eu nunca usei Crocs.",
    "Eu nunca vomitei na frente de outras pessoas.",
    "Eu nunca soltei pum em um elevador e fingi que não fui eu.",
    "Eu nunca segui a pessoa errada na rua.",
    "Eu nunca deixei meu celular cair na privada.",
    "Eu nunca fui em uma festa sem ser chamado.",
    "Eu nunca beijei alguém famoso.",
    "Eu nunca fiquei com gêmeos.",
    "Eu nunca vomitei e tive que engolir.",
    "Eu nunca gostei mais de um filme do que do seu livro.",
    "Eu nunca entrei em casa pela janela.",
    "Eu nunca ri tanto que fiz um pouco de xixi.",
    "Eu nunca menti para alguém sobre qual era meu nome.",
    "Eu nunca tive o meu nome no SPC.",
    "Eu nunca precisei ir ao médico devido a um objeto estranho preso em meu nariz ou ouvido.",
    "Eu nunca usei identidade falsa para entrar em uma festa.",
    "Eu nunca pesquisei meu nome no Google.",
    "Eu nunca dei de presente algo que ganhei e não gostei.",
    "Eu nunca convenci um amigo a largar a namorada.",
    "Eu nunca apaguei um post porque teve poucas curtidas.",
    "Eu nunca usei a escova de dentes de outra pessoa.",
    "Eu nunca me inscrevi em um reality show.",
    "Eu nunca culpei outra pessoa por um erro meu.",
    "Eu nunca menti sobre um candidato em que votei.",
    "Eu nunca dei um conselho ruim para alguém de propósito.",
    "Eu nunca dei em cima do namorado(a) de algum amigo.",
    "Eu nunca disse eu te amo para alguém que eu não amava de verdade.",
    "Eu nunca passei a madrugada mandando mensagem para alguém.",
    "Eu nunca fui ignorado no WhatsApp por alguém que eu gostava.",
    "Eu nunca inventei boatos sobre um(a) ex-namorado(a).",
    "Eu nunca traí alguém.",
    "Eu nunca implorei para algum(a) ex voltar para mim.",
    "Eu nunca estive um relacionamento aberto.",
    "Eu nunca tive um namorado virtual.",
    "Eu nunca me arrependi de ter namorado alguém.",
    "Eu nunca duvidei sobre minha orientação sexual.",
    "Eu nunca namorei uma pessoa para tentar esquecer outra.",
    "Eu nunca sumi depois de um primeiro encontro ruim.",
    "Eu nunca fiquei com alguém comprometido(a).",
    "Eu nunca terminei com alguém por mensagem.",
    "Eu nunca menti sobre meu estado civil.",
    "Eu nunca fingi receber uma mensagem/ligação para sair de um encontro ruim.",
    "Eu nunca falei sobre meu ex em um primeiro encontro.",
    "Eu nunca fiquei com mais de uma pessoa ao mesmo tempo.",
    "Eu nunca dirigi bêbado.",
    "Eu nunca fiquei com uma pessoa e depois nunca mais falei com ela.",
    "Eu nunca vi algum vizinho sem roupa.",
    "Eu nunca usei o Tinder.",
    "Eu nunca fiquei com gêmeos.",
    "Eu nunca marquei de ficar com alguém do Tinder.",
    "Eu nunca fiquei com alguém no banheiro de uma festa.",
    "Eu nunca fiquei com alguém na praia.",
    "Eu nunca fiquei com alguém na rua.",
    "Eu nunca mandei fotos ousadas para alguém.",
    "Eu nunca mandei a mesma foto ousada para duas pessoas ao mesmo tempo.",
    "Eu nunca tive um sonho quente com alguém que está aqui.",
    "Eu nunca tive um sonho quente com algum professor.",
    "Eu nunca fiquei tão louco que esqueci o próprio nome.",
    "Eu nunca fui carregado para casa depois de dar PT.",
    "Eu nunca enviei fotos ousadas para a pessoa errada.",
    "Eu nunca fiquei com alguém na cama dos meus pais.",
    "Eu nunca dancei especialmente para alguém.",
    "Eu nunca usei o Tinder enquanto namorava.",
    "Eu nunca fui num clube para adultos.",
    "Eu nunca faltei ao trabalho porque estava morrendo de ressaca.",
    "Eu nunca fiquei com alguém que eu nem sabia o nome.",
    "Eu nunca fiquei com alguém desta roda.",
    "Eu nunca tirei a roupa em uma festa.",
    "Eu nunca tive um \"amigo colorido\" ou \"amigo com benefícios\".",
    "Eu nunca fiquei com alguém na universidade.",
    "Eu nunca fingi estar sóbrio na frente dos meus pais.",
    "Eu nunca acordei e ainda estava bêbado.",
    "Eu nunca nadei sem roupa em uma praia ou cachoeira.",
    "Eu nunca dei um beijo triplo.",
    "Eu nunca fiquei com alguém em um carro.",
    "Eu nunca beijei alguém depois de ter vomitado.",
    "Eu nunca fui trabalhar bêbado.",
    "Eu nunca dancei em cima de uma mesa.",
    "Eu nunca dei só uma \"passadinha\" na casa do ex ou do crush.",
    "Eu nunca paguei por conteúdos adultos.",
    "Eu nunca recebi fotos ousadas sem estar esperando."
];
questions.fr = [
    "Je n’ai jamais séché l’école ou le travail",
    "Je n’ai jamais fait de moto",
    "Je n’ai jamais perdu un pari",
    "Je n’ai jamais fait de bain de minuit",
    "Je n’ai jamais trompé quelqu’un",
    "Je n’ai jamais chanté au karaoké",
    "Je ne me suis jamais cassé un os",
    "Je n’ai jamais vécu seul(e)",
    "Je n’ai jamais été sur un bateau",
    "Je n’ai jamais conduit une boîte de vitesses manuelle",
    "Je n’ai jamais utilisé de fausse carte d’identité",
    "Je n’ai jamais rompu avec quelqu’un",
    "Je n’ai jamais eu de grosse gueule de bois",
    "Je n’ai jamais embrassé quelqu’un en public",
    "Je ne me suis jamais battu en public",
    "Je n’ai jamais fait l’impasse sur une facture",
    "Je n’ai jamais gagné à la loterie",
    "Je n’ai jamais eu à aller au tribunal",
    "Je n’ai jamais été à un mariage à destination",
    "Je n’ai jamais menti à un patron",
    "Je ne me suis jamais planté à un mariage",
    "Je n’ai jamais embrassé plus d’une personne en heures",
    "Je n’ai jamais fait de farce à quelqu’un",
    "Je n’ai jamais eu d’aventure d’un soir",
    "Je n’ai jamais offert un nouveau cadeau",
    "Je n’ai jamais espionné quelqu’un sur les réseaux sociaux",
    "Je n’ai jamais grimpé par la fenêtre",
    "Je n’ai jamais roulé sur un trottoir",
    "Je n’ai jamais ri au point de faire pipi dans mon pantalon en tant qu’adulte",
    "Je ne suis jamais monté dans le mauvais train ou bus",
    "Je n’ai jamais envoyé de sexto",
    "Je n’ai jamais juré dans un lieu de culte",
    "Je n’ai jamais fouillé dans les affaires de quelqu’un",
    "Je n’ai jamais fumé de la marijuana",
    "Je n’ai jamais passé heures sans me doucher",
    "Je n’ai jamais eu à faire une marche de la honte",
    "Je n’ai jamais pris de vacances en solo",
    "Je n’ai jamais fait de road trip",
    "Je n’ai jamais mangé une pizza entière tout(e) seul(e)",
    "Je n’ai jamais sauvé une vie",
    "Je n’ai jamais eu de tatouage",
    "Je n’ai jamais voulu participer à une émission de télé-réalité",
    "Je n’ai jamais allumé un feu",
    "Je n’ai jamais été arrêté par la sécurité d’un aéroport",
    "Je n’ai jamais été viral en ligne",
    "Je n’ai jamais jeté de chewing-gum dans un espace public",
    "Je n’ai jamais dormi dehors pendant toute une nuit",
    "Je n’ai jamais couru un marathon",
    "Je n’ai jamais donné/reçu un lap dance",
    "Je n’ai jamais fait de discours devant personnes ou plus",
    "Je n’ai jamais fait pipi dans une piscine publique",
    "Je n’ai jamais menti à ma meilleure amie sur la personne avec qui j’étais",
    "Je ne suis jamais allé à Disneyland",
    "Je n’ai jamais fait de plan à trois",
    "Je n’ai jamais laissé quelqu’un en plan",
    "Je ne me suis jamais endormi pendant un rapport sexuel",
    "Je n’ai jamais menti sur mon âge",
    "Je n’ai jamais inventé une histoire sur quelqu’un qui n’était pas vraie",
    "Je n’ai jamais cru que quelque chose était hanté",
    "Je n’ai jamais participé à une manifestation",
    "Je n’ai jamais eu de paralysie du sommeil",
    "Je n’ai jamais été l’alibi d’un ami menteur",
    "Je n’ai jamais fait une nuit blanche",
    "Je n’ai jamais fait de jeu de rôle",
    "Je n’ai jamais regretté une excuse",
    "Je n’ai jamais fait semblant d’être malade pour attirer l’attention",
    "Je n’ai jamais détesté un plat que j’avais cuisiné",
    "Je n’ai jamais supprimé un post sur les réseaux sociaux parce qu’il n’avait pas reçu assez de likes",
    "Je n’ai jamais dépensé plus de euros pour un haut",
    "Je n’ai jamais jeté un verre sur quelqu’un",
    "Je n’ai jamais porté les sous-vêtements de quelqu’un d’autre",
    "Je n’ai jamais voyagé en Europe",
    "Je n’ai jamais tenté un régime à la mode",
    "Je ne suis jamais allé dans un club de strip-tease",
    "Je n’ai jamais regardé une série entière en une journée",
    "Je n’ai jamais essayé les psychédéliques",
    "Je n’ai jamais rencontré quelqu’un de célèbre",
    "Je n’ai jamais fait d’exhibitionnisme",
    "Je n’ai jamais fait partie d’une équipe sportive",
    "Je n’ai jamais dépassé le plafond d’une carte de crédit",
    "Je n’ai jamais été ivre mort(e)",
    "Je n’ai jamais été fiancé(e)",
    "Je ne me suis jamais marié(e)",
    "Je n’ai jamais fait de dons à une organisation caritative",
    "Je n’ai jamais fait semblant d’être malade pour me sortir de quelque chose",
    "Je n’ai jamais posé un lapin à un rendez-vous",
    "Je n’ai jamais ghosté quelqu’un",
    "Je n’ai jamais fait l’amour sur une plage",
    "Je ne suis jamais tombé(e) amoureux(se)",
    "Je n’ai jamais trompé mon partenaire",
    "Je n’ai jamais pris de bain de minuit",
    "Je n’ai jamais fait semblant d’être malade au travail",
    "Je n’ai jamais triché à un examen",
    "Je n’ai jamais mis mon compte en banque à découvert",
    "Je n’ai jamais mangé le repas de quelqu’un d’autre au boulot",
    "Je n’ai jamais joué au strip-poker",
    "Je n’ai jamais fumé un joint",
    "Je n’ai jamais essayé les drogues dures",
    "Je ne me suis jamais endormi dans un lieu public",
    "Je ne me suis jamais endormi au travail",
    "Je n’ai jamais menti sur mon CV",
    "Je n’ai jamais appelé mon ex en état d’ébriété",
    "Je n’ai jamais pris de l’acide",
    "Je n’ai jamais eu un coup d’un soir",
    "Je n’ai jamais lu les messages textes d’un partenaire",
    "Je n’ai jamais lu les courriels d’un partenaire",
    "Je n’ai jamais été hospitalisé(e) pour autre chose que pour accoucher",
    "Je n’ai jamais chanté en public",
    "Je n’ai jamais joué d’un instrument de musique",
    "Je n’ai jamais fait de snowboard",
    "Je n’ai jamais fait de ski",
    "Je n’ai jamais voyagé dans un pays étranger",
    "Je n’ai jamais appris une langue étrangère",
    "Je n’ai jamais accepté un verre d’un étranger",
    "Je n’ai jamais menti sur mes revenus",
    "Je n’ai jamais été pris(e) en flagrant délit dans un lieu public",
    "Je n’ai jamais été nu(e) en public",
    "Je ne suis jamais sorti(e) avec quelqu’un qui avait ans de plus que moi",
    "Je ne suis jamais sorti(e)avec quelqu’un de 5 ans plus jeune",
    "Je n’ai jamais envoyé de SMS ou pris un appel au cinéma",
    "Je n’ai jamais convaincu un ami de larguer son partenaire",
    "Je n’ai jamais convaincu un partenaire de larguer un ami",
    "Je n’ai jamais été l’alibi de quelqu’un d’autre",
    "Je n’ai jamais sauté un tourniquet",
    "Je n’ai jamais éternué(e) sur quelqu’un d’autre au travail",
    "Je n’ai jamais fait don d’un organe",
    "Je n’ai jamais menti à un agent de la force publique",
    "Je n’ai jamais été demoiselle d’honneur",
    "Je n’ai jamais été témoin de mariage",
    "Je n’ai jamais appelé un partenaire par un mauvais nom",
    "Jamais je n’ai pensé que le bébé d’une amie était moche",
    "Je n’ai jamais gagné plus de euros au jeu",
    "Je n’ai jamais perdu plus de euros au jeu",
    "Je n’ai jamais été végétarien(ne)",
    "Je n’ai jamais utilisé de fausse carte d’identité",
    "Je n’ai jamais menti sur mon âge",
    "Je n’ai jamais fait de rêve lucide",
    "Je n’ai jamais fait campagne pour un candidat politique",
    "Je n’ai jamais eu la varicelle",
    "Je n’ai jamais flashé sur quelqu’un",
    "Je n’ai jamais montré mes fesses à quelqu’un",
    "Je n’ai jamais menti à mon meilleur ami",
    "Je n’ai jamais eu un incident de rage au volant",
    "Je n’ai jamais fait exprès de couper la file d’attente",
    "Je n’ai jamais gardé rancune plus d’un an",
    "Je n’ai jamais laissé échapper quelque chose que j’avais juré de garder secret",
    "Je n’ai jamais gâché les vacances de quelqu’un d’autre",
    "Jamais je ne me suis cassé une dent",
    "Je n’ai jamais essayé un régime à la mode",
    "Je ne me suis jamais coupé les cheveux tout(e) seul(e)",
    "Je n’ai jamais été éveillé(e) pendant heures d’affilée ou plus",
    "Je n’ai jamais dit accidentellement « Je t’aime » à quelqu’un",
    "Je n’ai jamais pleuré ou flirté pour éviter une contravention",
    "Je n’ai jamais fouillé dans la chambre, les armoires ou la propriété d’un ami",
    "Je n’ai jamais fait l’amour dans une voiture",
    "Je n’ai jamais travaillé avec quelqu’un que je ne pouvais pas supporter",
    "Je n’ai jamais eu d’ami avec des avantages",
    "Je n’ai jamais mangé de nourriture qui ne respecte pas la règle des cinq secondes",
    "Je n’ai jamais passé une journée entière à regarder la télé-réalité",
    "Je n’ai jamais envoyé de photos de moi nu(e)",
    "Je n’ai jamais reçu de nus",
    "Je n’ai jamais pensé qu’un personnage de dessin animé était sexy",
    "Je n’ai jamais Googlé quelqu’un avant un rendez-vous",
    "Je ne me suis jamais incrusté dans une fête ou un mariage",
    "Je ne suis jamais sortie avec un musicien",
    "Je n’ai jamais eu de rendez-vous à l’aveugle",
    "Je n’ai jamais eu ou donné un suçon",
    "Je ne me suis jamais blessé(e) au lit pendant les galipettes",
    "Je n’ai jamais vu quelqu’un mourir",
    "Je n’ai jamais eu de problème de garde-robe",
    "Je n’ai jamais couru pour ma vie",
    "Je n’ai jamais participé à un concours de talents",
    "Je n’ai jamais eu de points de suture",
    "Je n’ai jamais essayé de rendre un ex jaloux",
    "Je n’ai jamais conduit une boîte de vitesses manuelle",
    "Je n’ai jamais mis le feu à quelque chose en cuisinant",
    "Je n’ai jamais organisé un rendez-vous avec un ami",
    "Je n’ai jamais lancé un hashtag",
    "Je n’ai jamais payé pour du contenu pour adultes",
    "Je n’ai jamais fait de plongée sous-marine",
    "Je n’ai jamais fréquenté quelqu’un du même sexe ou du même genre",
    "Je n’ai jamais espionné en voiture la maison d’un ex ou d’un amoureux",
    "Je n’ai jamais dansé sous la pluie",
    "Je n’ai jamais dansé sur une table",
    "Je n’ai jamais rejoint le mile-high club",
    "Je n’ai jamais dormi dans ma voiture",
    "Je ne suis jamais passé à la télévision",
    "Je n’ai jamais eu d’engelures",
    "Je n’ai jamais eu de coup de soleil brûlant",
    "Je n’ai jamais été malade lors d’un rendez-vous",
    "Je n’ai jamais eu d’empoisonnement alimentaire",
    "Je n’ai jamais donné intentionnellement de mauvais conseils à quelqu’un",
    "Je n’ai jamais chahuté un spectacle en direct",
    "Je n’ai jamais subi de chirurgie",
    "Je n’ai jamais heurté une voiture en stationnement",
    "Je n’ai jamais organisé une fête surprise pour quelqu’un d’autre",
    "Je n’ai jamais eu de fête surprise organisée pour moi",
    "Je n’ai jamais porté de perruque ou d’extensions",
    "Je ne me suis jamais habillé en drag queen",
    "Je n’ai jamais fouillé dans les poubelles",
    "Je n’ai jamais rendu quelque chose après l’avoir porté",
    "Je n’ai jamais fait pipi dans mon pantalon à l’âge adulte",
    "Je n’ai jamais été dans un hélicoptère",
    "Je n’ai jamais perdu mes chaussures pendant une soirée",
    "Je ne me suis jamais garé sur une place pour handicapés",
    "Je n’ai jamais flirté avec une personne mariée",
    "Je n’ai jamais remis en question une relation",
    "Je n’ai jamais eu d’appareil dentaire",
    "Je n’ai jamais eu de carie",
    "Je n’ai jamais fait d’auto-stop",
    "Je n’ai jamais pris un auto-stoppeur",
    "Je n’ai jamais changé un pneu",
    "Je n’ai jamais menti sur mon statut relationnel",
    "Je n’ai jamais menti sur un profil de rencontre",
    "Je n’ai jamais eu le mal de mer",
    "Je n’ai jamais eu le cœur brisé",
    "Je n’ai jamais brisé le cœur de quelqu’un d’autre",
    "Je n’ai jamais eu le coup de foudre",
    "Je n’ai jamais éternué sur un étranger",
    "Je n’ai jamais vomi en public",
    "Je n’ai jamais souhaité avoir des enfants",
    "Je n’ai jamais souhaité ne pas avoir d’enfants",
    "Je n’ai jamais vu quelque chose d’effrayant dans les transports en commun",
    "Je n’ai jamais envoyé de sexto à un ex",
    "Je n’ai jamais envoyé un sexto à la mauvaise personne",
    "Je n’ai jamais mis de chewing-gum dans mes cheveux",
    "Je n’ai jamais surpris mes parents en train de le faire",
    "Je n’ai jamais mangé un paquet entier d’Oreos en une seule fois",
    "Je n’ai jamais bu une bouteille de vin entière",
    "Je n’ai jamais été témoin d’un crime",
    "Je ne suis jamais monté à cheval",
    "Je ne me suis jamais évanoui(e)",
    "Je n’ai jamais bouché les toilettes",
    "Je n’ai jamais fait de camping",
    "Je n’ai jamais donné mon sang",
    "Je ne me suis jamais battu physiquement",
    "Je n’ai jamais surveillé l’ex de mon partenaire sur les réseaux sociaux",
    "Je n’ai jamais filmé un moment intime",
    "Je n’ai jamais tiré avec une arme à feux",
    "Je n’ai jamais fait tomber un bébé",
    "Je n’ai jamais couru un marathon",
    "Je n’ai jamais menti sur la personne pour laquelle j’ai voté",
    "Je n’ai jamais partagé une nouvelle sans lire au-delà du titre",
    "Je n’ai jamais été licencié d’un emploi",
    "Je ne me suis jamais disputé avec un partenaire en public",
    "Je n’ai jamais battu un jeu vidéo",
    "Je n’ai jamais flirté avec un serveur ou un barman",
    "Je n’ai jamais été serveur de tables",
    "Je n’ai jamais travaillé dans le commerce de détail",
    "Je n’ai jamais brûlé un feu rouge",
    "Je n’ai jamais été trompé(e)",
    "Je n’ai jamais fait l’objet d’une rumeur qui n’était pas vraie",
    "Je n’ai jamais répandu une rumeur que je savais fausse",
    "Je n’ai jamais rencontré une célébrité",
    "Je n’ai jamais donné moins de % de pourboire",
    "Je n’ai jamais donné plus de % de pourboire",
    "Je n’ai jamais pleuré à une fête",
    "Je n’ai jamais pleuré au travail",
    "Je n’ai jamais pleuré en public",
    "Je n’ai jamais utilisé les toilettes d’une station-service",
    "Je ne suis jamais allé(e) au travail avec la gueule de bois",
    "Je n’ai jamais juré devant un beau-parent",
    "Je n’ai jamais juré contre un membre de ma belle-famille",
    "Je ne me suis jamais produit sur scène",
    "Je n’ai jamais ri à un enterrement",
    "Je n’ai jamais donné à quelqu’un un faux numéro de téléphone",
    "Je n’ai jamais laissé un commentaire méchant sur YouTube",
    "Je ne suis jamais monté dans une voiture de police",
    "Je n’ai jamais fait de croisière",
    "Je n’ai jamais visité une plage nudiste",
    "Je n’ai jamais juré devant un enfant",
    "Je n’ai jamais appelé les flics pour quelqu’un d’autre",
    "Je n’ai jamais volé à l’étalage",
    "Je n’ai jamais fait de saut à l’élastique",
    "Je n’ai jamais passé plus de trois jours sans me doucher",
    "Je n’ai jamais passé plus d’un jour sans me brosser les dents",
    "Je n’ai jamais été « ghosté » par quelqu’un",
    "Je n’ai jamais reproché à quelqu’un d’autre une erreur au travail",
    "Je ne me suis jamais attribué le mérite du travail de quelqu’un d’autre"
];
questions.de = [
    "Ich bin noch nie mit all meinen Kleidern in einen Pool gesprungen.",
    "Ich bin noch nie nach drei Uhr morgens draußen geblieben.",
    "Ich habe noch nie ganz alleine gelebt.",
    "Ich wurde noch nie von einem Job entlassen.",
    "Ich habe noch nie den ganzen Tag ferngesehen.",
    "Ich habe noch nie einen Knochen gebrochen.",
    "Ich habe noch nie krank vorgetäuscht, die Schule oder die Arbeit verpasst zu haben.",
    "Ich habe noch nie ein Geschenk verschenkt.",
    "Ich habe noch nie einen Freund in den sozialen Medien entfolgt.",
    "Ich musste noch nie vor einer Menschenmenge eine Rede halten.",
    "Ich bin noch nie einen Marathon gelaufen.",
    "Ich habe noch nie Gewichte für ein Training gehoben.",
    "Ich bin noch nie online viral geworden.",
    "Ich habe noch nie ein Tattoo bekommen.",
    "Ich habe noch nie eine Jury-Pflicht erfüllt.",
    "Ich habe noch nie jemandem das Leben gerettet.",
    "Ich habe noch nie ein Rezept aus einem Blog gemacht.",
    "Ich habe noch nie eine berühmte Person auf der Straße gesehen.",
    "Ich habe noch nie eine Mahlzeit in einem Restaurant zurückgeschickt.",
    "Ich habe noch nie eine Entschuldigung bereut.",
    "Ich habe meinem besten Freund noch nie gelogen.",
    "Ich bin noch nie außerhalb des Landes gereist.",
    "Ich habe noch nie in der Schule einen All-Nighter gezogen.",
    "Ich habe noch nie über mein Alter gelogen.",
    "Ich habe mir noch nie eine Geschichte ausgedacht, um jemanden zu beeindrucken.",
    "Niemals habe ich meine Eltern belogen, wohin ich gehe.",
    "Ich habe meinem Geschwister noch nie etwas gekauft, was ich eigentlich nicht hätte kaufen sollen.",
    "Ich habe noch nie den Geburtstag eines Familienmitglieds vergessen.",
    "Ich habe mich nie aus dem Haus geschlichen.",
    "Ich habe noch nie einem Familienmitglied Geld gestohlen.",
    "Ich habe noch nie in den Wald gepinkelt.",
    "Ich habe noch nie an einem Tag eine ganze Netflix-Serie gespielt.",
    "Ich habe noch nie das Netflix-Passwort meiner Eltern verwendet.",
    "Ich habe noch nie einem Geschwister Kleidung gestohlen.",
    "Ich habe nie so getan, als würde ich schlafen, also musste ich nicht mit etwas helfen.",
    "Ich bin noch nie bei einer Familienfeier beschwipst aufgetaucht.",
    "Ich habe noch nie schmutzige Unterwäsche getragen.",
    "Ich habe noch nie zwei Tage hintereinander die gleiche Trainingskleidung getragen.",
    "Ich habe den Hund noch nie vom Tisch gefüttert.",
    "Ich habe noch nie an einem Tag ein ganzes Buch gelesen.",
    "Niemals habe ich jemals nicht für einen Test studiert.",
    "Ich habe noch nie alte Heimvideos wiedergesehen.",
    "Ich hatte noch nie jemanden im Haus meiner Eltern, ohne dass sie es wussten.",
    "Ich habe noch nie eine Mahlzeit für die ganze Familie gekocht.",
    "Niemals habe ich mein Essen ausgespuckt, als die Person, die es gemacht hat, nicht hinschaute.",
    "Ich habe noch nie die Kreditkarte eines Elternteils gestohlen.",
    "Ich war noch nie in einem Disney Park.",
    "Ich bin noch nie in einen physischen Kampf mit einem Geschwister geraten.",
    "Niemals habe ich absichtlich einen Geschwisterschrei gemacht.",
    "Ich habe noch nie einen Blumenstrauß für jemanden gekauft.",
    "Ich bin noch nie dünn getaucht.",
    "Ich habe noch nie einen Test betrogen.",
    "Ich habe noch nie über Arbeit gelogen, um aus sozialen Plänen herauszukommen.",
    "Ich habe meinen Standort noch nie mit einem Freund geteilt.",
    "Ich war noch nie in den Partner eines Freundes verknallt.",
    "Ich wurde noch nie verhaftet.",
    "Ich habe noch nie kostenlose Getränke an einer Bar erhalten.",
    "Ich habe noch nie in 24 Stunden mehr als eine Person geküsst.",
    "Ich war noch nie auf einem Kreuzfahrtschiff.",
    "Ich habe mir noch nie eine Geschichte über jemanden ausgedacht, der nicht real war.",
    "Ich habe noch nie einen Ex-Partner in den sozialen Medien verfolgt.",
    "Ich bin noch nie alleine in eine Bar oder einen Club gegangen.",
    "Ich habe noch nie für das Abendessen aller anderen bezahlt.",
    "Ich habe noch nie einen Ex-Partner erwischt, der mich betrogen hat.",
    "Ich habe noch nie mein eigenes Brot gebacken.",
    "Ich habe noch nie eine Überraschungsparty veranstaltet.",
    "Ich habe noch nie ein anonymes Geschenk erhalten.",
    "Ich bin noch nie zu einem Rave oder Musikfestival gegangen.",
    "Ich wurde noch nie zu einem Konzert auf die Bühne eingeladen.",
    "Ich bin noch nie in einer TV-Show aufgetreten.",
    "Ich habe mich in meiner Periode noch nie krank gemeldet.",
    "Ich habe noch nie nach Mitternacht Pizza bestellt.",
    "Ich habe noch nie die Reste eines anderen gegessen.",
    "Ich habe mich noch nie über einen Mitbewohner beschwert.",
    "Ich habe noch nie im Bett meines Mitbewohners geschlafen.",
    "Ich habe mich nie länger als ein Jahr mit jemandem verabredet.",
    "Ich habe noch nie mit einem bedeutenden Anderen zusammengelebt.",
    "Ich hatte noch nie Sex draußen.",
    "Ich hatte noch nie einen Dreier.",
    "Ich habe noch nie mit jemandem in einem Kino rumgemacht.",
    "Ich habe noch nie jemanden getroffen, der älter als fünf Jahre ist als ich.",
    "Ich habe noch nie jemanden getroffen, der mehr als fünf Jahre jünger ist als ich.",
    "Ich hatte noch nie Sex in der Öffentlichkeit.",
    "Ich war noch nie in einem Sexspielzeuggeschäft.",
    "Ich habe noch nie eine ganze Nacht draußen geschlafen.",
    "Ich habe noch nie jemanden getroffen, der berühmt ist.",
    "Ich habe noch nie mit jemandem im Bett eines Mitbewohners geschlafen.",
    "Ich war noch nie in die S.O. eines Freundes verknallt..",
    "Ich war noch nie verliebt.",
    "Ich habe noch nie [Spielzeug vom Typ X] ​​benutzt..",
    "Niemals hatte ich jemals Analsex.",
    "Ich bin noch nie in einen Stripclub gegangen.",
    "Ich habe noch nie eine Rolle gespielt.",
    "Ich habe noch nie einen Lapdance gegeben.",
    "Ich hatte noch nie FaceTime-Sex.",
    "Ich habe noch nie am Telefon meines Partners geschnüffelt.",
    "Ich habe noch nie einen neuen Partner eines Ex beschnüffelt.",
    "Ich habe noch nie einen bedeutenden Anderen angelogen.",
    "Ich habe noch nie jemanden betrogen.",
    "Ich habe noch nie Nacktbilder geschickt",
    "Ich habe noch nie eine Berühmtheit getroffen.",
    "Ich habe noch nie in der Öffentlichkeit gespuckt.",
    "Ich habe noch nie einen Text an die falsche Person geschickt.",
    "Ich habe noch nie versucht, einen Schwarm zu beeindrucken, indem ich vorgab, Dinge zu mögen, die sie mochten.",
    "Noch nie hatte ich Kopfläuse.",
    "Noch nie war ich so betrunken.",
    "Noch nie habe ich in der Öffentlichkeit so laut gefurzt.,",
    "Noch nie habe ich so hart gelacht, ich habe mich gepinkelt.",
    "Noch nie habe ich Kaugummi unter einen Tisch gelegt.",
    "Noch nie habe ich versucht, ein Fass Stand zu tun.",
    "Ich habe noch nie in einen Pool gepinkelt.",
    "Ich habe noch nie die Zählung verloren, wie viele Getränke ich getrunken habe.",
    "Noch nie habe ich mich öffentlich geäußert.",
    "Noch nie habe ich die „Fünf-Sekunden-Regel“ gebrochen.",
    "Noch nie wurde ich überfahren.",
    "Noch nie habe ich einen Ex angerufen oder getextet.",
    "Noch nie habe ich bei jemandem die Polizei gerufen.",
    "Ich habe noch nie auf einem Ex online lauerte.,",
    "Ich habe noch nie etwas gestohlen.",
    "Ich habe noch nie in der Öffentlichkeit gepinkelt.",
    "Nie habe ich in der Schule oder bei der Arbeit geweint.",
    "Ich habe noch nie eine gefälschte ID verwendet.",
    "Noch nie bin ich nach einem Kuss aufgesprungen.",
    "Ich habe noch nie etwas auf einem Teller gegessen.",
    "Noch nie habe ich Musik oder Filme illegal heruntergeladen.",
    "Ich habe noch nie Medikamente genommen, die mir nicht verschrieben wurden.",
    "Noch nie habe ich jemanden abgeladen.",
    "Noch nie wurde ich abgeladen.",
    "Nie habe ich in der Öffentlichkeit geweint.",
    "Ich war noch nie high.",
    "Ich habe noch nie eine schlechte Karaoke-Nummer gemacht.",
    "Noch nie habe ich mich selbst gepisst.",
    "Noch nie habe ich eine kitschige Pick up Linie benutzt.",
    "Nie habe ich ein Bad verlassen, ohne mir die Hände zu waschen.",
    "Nie habe ich jemals mit einem Freund Ex bekommen.",
    "Noch nie habe ich einen Drink auf jemanden geworfen.",
    "Noch nie hatte ich ein schlechtes Date.",
    "Ich habe noch nie einen Schwarm online verfolgt.",
    "Noch nie habe ich einen neuen bae Ex gegoogelt.",
    "Noch nie habe ich ein Blind Date recherchiert.",
    "Noch nie bin ich in einen physischen Kampf geraten.",
    "Noch nie habe ich in meinem Lebenslauf gelogen.",
    "Noch nie hatte ich einen schlechten Farbstoffjob.",
    "Noch nie habe ich alle meine Halloween Süßigkeiten in einer Sitzung gegessen.",
    "Noch nie habe ich mich von jemand anderem für meinen stinkenden Furz fallen lassen.",
    "Ich habe noch nie geflirtet, um in Schwierigkeiten zu geraten.",
    "Noch nie habe ich während eines Vorstellungsgesprächs komplett über eine Fähigkeit gelogen.",
    "Noch nie habe ich eine Show im Voraus gesehen und bae darüber angelogen.",
    "Nie war ich länger als 24 Stunden wach.",
    "Noch nie habe ich ein Geschenk, das mir gegeben wurde, neu geschenkt.",
    "Noch nie war ich Fallschirmspringen.",
    "Noch nie hatte ich eine Nahtoderfahrung.",
    "Noch nie habe ich eine ganze Pizza alleine gegessen.",
    "Noch nie habe ich Essen aus einem Mülleimer gegessen.",
    "Noch nie bin ich mit einem Hubschrauber geflogen.",
    "Noch nie war ich seekrank.",
    "Noch nie habe ich Alligator ausprobiert.",
    "Noch nie habe ich jemals auf Niesen.",
    "Ich habe noch nie alle Harry-Potter-Serien gelesen.",
    "Noch nie hatte ich Durchfall und Erbrechen gleichzeitig.",
    "Noch nie habe ich in einem Aufzug gefurzt und so getan, als wäre ich es nicht.",
    "Noch nie bin ich versehentlich in etwas hineingegangen und habe einen Zeh gebrochen/ausgerenkt.",
    "Nie habe ich jemals gegangen commando.",
    "Noch nie habe ich Strip Poker gespielt.",
    "Noch nie habe ich mich mit jemandem getroffen, nur um jemanden eifersüchtig zu machen.",
    "Noch nie wurde ich von meinen Eltern betreten.",
    "Noch nie hatte ich einen Freund mit Vorteilen.",
    "Noch nie musste ich einen Hickey vertuschen.",
    "Noch nie habe ich einen Körperschuss gemacht.",
    "Nie habe ich jemals meine Knöpfe repariert, je nachdem, wen ich an diesem Tag sehen würde.",
    "Noch nie hatte ich ein Sex Tape.",
    "Noch nie bin ich dünn getaucht.",
    "Ich habe noch nie sextet.",
    "Noch nie habe ich es gefälscht.",
    "Noch nie habe ich mit Schlagsahne gespielt.",
    "Ich habe noch nie Akte geschickt.",
    "Ich habe mich noch nie von den Eltern eines Freundes oder Partners angezogen gefühlt.",
    "Noch nie habe ich ein aromatisiertes Kondom probiert.",
    "Noch nie hatte ich einen One Night Stand.",
    "Noch nie hatte ich Sex an einem öffentlichen Ort.",
    "Ich habe noch nie jemanden gesehen, der Sex hat.",
    "Noch nie habe ich einen schmutzigen Text an die falsche Person geschickt.",
    "Ich habe noch nie mit einem Lehrer/College-Professor geflirtet.",
    "Noch nie hatte ich beim ersten Date Sex.",
    "Noch nie wurde ich betrogen.",
    "Nie habe ich mehr als eine Person an einem Tag geküsst.",
    "Noch nie hatte ich schlechten Sex.",
    "Noch nie bin ich beim Anschauen von Pornos eingeschlafen.",
    "Ich habe noch nie von jemandem in diesem Kreis geträumt.",
    "Noch nie hatte ich Sex mit anderen Menschen im Zimmer.",
    "Noch nie habe ich jemanden geflasht.",
    "Noch nie bin ich dem mile-high Club beigetreten.",
    "Ich habe noch nie hooky von der Schule oder Arbeit gespielt.",
    "Noch nie bin ich Motorrad gefahren.",
    "Ich habe noch nie eine Wette verloren.",
    "Noch nie habe ich mir einen Knochen gebrochen.",
    "Nie habe ich allein gelebt.",
    "Noch nie bin ich betrunken gefahren.",
    "Ich habe noch nie experimentiert, um meine sexuelle Orientierung zu sehen.",
    "Nie habe ich je gesagt 'Ich liebe dich' nur um gelegt.",
    "Noch nie habe ich meine Nachbarn ausspioniert.",
    "Nie habe ich an meiner Heterosexualität gezweifelt.",
    "Noch nie habe ich mich über jemanden lustig gemacht.",
    "Ich habe noch nie einen Ex-Freund oder Freundin auf Social Media verfolgt.",
    "Noch nie habe ich keeping up with the Kardashians gesehen."
];
questions.gr = [
    "Ποτέ δεν προσποιήθηκα ότι είμαι άρρωστος για να αποφύγω το σχολείο.",
    "Ποτέ δεν έχω εκφοβίσει συμμαθητή.",
    "Ποτέ δεν μου επέλεξε τελευταία για ένα ομαδικό έργο.",
    "Ποτέ δεν έχω ξαναγυρίσει κατά τη διάρκεια σχολικής εκδρομής.",
    "Ποτέ δεν έχω φλερτάρει με τον δάσκαλό μου.",
    "Ποτέ δεν ήμουν ποτέ στο χορό.",
    "Ποτέ δεν έχω ορκιστεί ποτέ σε συμμαθητή.",
    "Ποτέ δεν έχω κλέψει ποτέ από έναν συμμαθητή.",
    "Ποτέ δεν έχω τραγουδήσει ποτέ στο ντους.",
    "Ποτέ δεν έχω δει ποτέ ταινία R-rated.",
    "Ποτέ δεν έχω ασκήσει πώς να φιλάω χρησιμοποιώντας το μαξιλάρι μου.",
    "Ποτέ δεν έχω παίξει ποτέ περιστρέψτε το μπουκάλι.",
    "Ποτέ δεν έχω γνωρίσει κάποιον διάσημο.",
    "Ποτέ δεν έχω παίξει ποτέ πόκερ.",
    "Ποτέ δεν έχω συνομιλήσει με έναν ξένο στο Διαδίκτυο.",
    "Ποτέ δεν ήμουν αργά για το σχολείο.",
    "Ποτέ δεν έχω παντελόνι παιδί.",
    "Ποτέ δεν έχω ξαφνιάσει μπροστά από έναν συμμαθητή .",
    "Ποτέ δεν είχα ποτέ δουλειά μερικής απασχόλησης.",
    "Ποτέ δεν είχα εξαπατήσει σε μια δοκιμή.",
    "Ποτέ δεν έχω κρύψει ποτέ φαγητό κάτω από το κρεβάτι μου.",
    "Ποτέ δεν έχω πέσει ποτέ και έπεσα στη μέση μιας συγκέντρωσης.",
    "Ποτέ δεν έχω κάνει ανόητα πρόσωπα στους γονείς και τους δασκάλους μου.",
    "Ποτέ δεν έχω τραγουδήσει ποτέ άθλια σε ένα μπάνιο.",
    "Ποτέ δεν έχω χορέψει ποτέ μπροστά από έναν καθρέφτη.",
    "Ποτέ δεν έβγαλα τα χαλαρά δόντια μου και τα έδειξα σε άλλους.",
    "Ποτέ δεν αναρωτήθηκα πώς είναι να είσαι γάτα.",
    "Ποτέ δεν έπεσα από το κρεβάτι ενώ κοιμόμουν.",
    "Ποτέ δεν έχω κλέψει ποτέ κρυφά χρήματα από την τσέπη του πατέρα μου.",
    "Ποτέ δεν δανείστηκα ποτέ τα στυλό του αδερφού μου χωρίς να ρωτήσω.",
    "Ποτέ δεν έχω σχεδιάσει ποτέ ένα αστείο καρτούν στο πρόσωπο του αδερφού μου ενώ κοιμόταν.",
    "Ποτέ δεν έχω πει ψέματα στους γονείς μου για το πώς η αδερφή μου τράβηξε τα μαλλιά μου όταν δεν το έκανε.",
    "Ποτέ δεν έχω φάει κάτι μέχρι να με αρρωστήσει.",
    "Ποτέ δεν ήμουν ποτέ στο νοσοκομείο.",
    "Ποτέ δεν έχω μάθει πώς να κολυμπάω.",
    "Ποτέ δεν έχω δει ποτέ αστέρι.",
    "Δεν έχω φορέσει ποτέ τυχαία κάλτσες.",
    "Ποτέ δεν είχα ποτέ ένα φοβερό κούρεμα.",
    "Ποτέ δεν έχω σπάσει ποτέ ένα κόκαλο.",
    "Ποτέ δεν έχω βγει ποτέ χωρίς να βουρτσίσω τα μαλλιά μου.",
    "Ποτέ δεν κοιμήθηκα ποτέ έξω όταν μεθύθη.",
    "Ποτέ δεν έχω πιει ουίσκι σαν νερό.",
    "Ποτέ δεν έχω πιει ποτέ κάλεσε κάποιον.",
    "Ποτέ δεν έχω πάει σπίτι σε λάθος σπίτι ενώ μεθύθηκα.",
    "Ποτέ δεν έχω παίξει ποτέ αθλήματα ενώ έπινα.",
    "Ποτέ δεν έχω κατηγορήσει το ποτό για κάτι που είπα.",
    "Ποτέ δεν είχα ποτέ τρόμο εγκυμοσύνης.",
    "Ποτέ δεν έπινα ποτέ ενώ οδηγούσα τις δημόσιες συγκοινωνίες.",
    "Ποτέ δεν έχω περάσει ποτέ από το ποτό.",
    "Ποτέ δεν έχω αλλάξει ποτέ τη λάμπα.",
    "Ποτέ δεν έπεσα ποτέ λόγω της κατανάλωσης αλκοόλ.",
    "Ποτέ δεν έχω παίξει ποτέ ένα ποτό.",
    "Ποτέ δεν έχω ανοίξει ποτέ ένα μπουκάλι με ένα άλλο μπουκάλι.",
    "Ποτέ δεν έχω πιει ποτέ μόνος μου.",
    "Ποτέ δεν ήμουν ποτέ μεθυσμένος για να κερδίσω εμπιστοσύνη.",
    "Ποτέ δεν έχω φάει ποτέ στρείδια.",
    "Ποτέ δεν έχω βουλώσει ποτέ μια μπύρα σε λιγότερο από δευτερόλεπτα και έπειτα τράβηξα.",
    "Ποτέ δεν έχω κάνει ένα σώμα σου.",
    "Ποτέ δεν έχω ποτέ κοκαλιάρικο.",
    "Ποτέ δεν ψήφισα ποτέ σε εκλογές.",
    "Ποτέ δεν μου δόθηκε κοσμήματα.",
    "Ποτέ δεν έχω κάνει ποτέ πρόταση γάμου.",
    "Ποτέ δεν έτρωγα ποτέ κάποιον με ένα κουτάλι.",
    "Ποτέ δεν έστειλα ποτέ σε κάποιο χαριτωμένο γραπτό μήνυμα το πρωί.",
    "Ποτέ δεν έχω δοκιμάσει ποτέ ραντεβού ταχύτητας.",
    "Ποτέ δεν έχω λάβει λουλούδια από κάποιον που χρονολογώ.",
    "Ποτέ δεν έχω περάσει ποτέ μια νύχτα με κάποιον στην παραλία.",
    "Ποτέ δεν ήμουν ποτέ σε μια μακρά οδήγηση με κάποιον που χρονολογώ.",
    "Ποτέ δεν έκανα ποτέ θέατρο.",
    "Ποτέ δεν είχα ποτέ ένα ρομαντικό δείπνο υπό το φως των κεριών.",
    "Ποτέ δεν προσπάθησα ποτέ να κλέψω τους κωδικούς πρόσβασης του συνεργάτη μου.",
    "Ποτέ δεν είχα ποτέ συντριβή στον σύντροφο του φίλου μου.",
    "Ποτέ δεν έχω καταδιώξει κάποιον στο Instagram.",
    "Ποτέ δεν μετανιώσατε ποτέ που χρονολογώ κάποιον.",
    "Ποτέ δεν προσπάθησα ποτέ να κρύψω ένα χακί.",
    "Ποτέ δεν μίλησα ποτέ με κάποιον όλη τη νύχτα.",
    "Ποτέ δεν ήμουν ποτέ φίλος.",
    "Ποτέ δεν έχω διαλυθεί με κάποιον πάνω από κείμενο.",
    "Ποτέ δεν φίλησα ποτέ κάποιον σε ασανσέρ.",
    "Ποτέ δεν έστειλα ποτέ σέξι selfie σε κάποιον.",
    "Ποτέ δεν έχω πάρει ποτέ τη μύτη μου.",
    "Ποτέ δεν έχω σπάσει ποτέ το κινητό μου τηλέφωνο.",
    "Ποτέ δεν μπήκα ποτέ σε κάποιον στο μπάνιο.",
    "Ποτέ δεν έχω πιάσει να κάνω ένα χορευτικό πάρτι μόνος μου μπροστά σε έναν καθρέφτη.",
    "Ποτέ δεν έχω βάλει ποτέ γλυκά στην τσέπη μου χωρίς χαρτοπετσέτα ή κάλυμμα ενώ ήμουν μεθυσμένος γιατί ήθελα να το δώσω αργότερα στον αδερφό μου.",
    "Ποτέ δεν έχω αφήσει ποτέ ένα μεθυσμένο τηλεφωνητή.",
    "Ποτέ δεν έχω στείλει κατά λάθος ένα κείμενο σε λάθος άτομο.",
    "Ποτέ δεν έχω τρυπήσει ποτέ έναν τοίχο και το μετανιώσαμε γιατί ήταν οδυνηρό.",
    "Ποτέ δεν έχω φάει κατά λάθος τροφή για σκύλους.",
    "Ποτέ δεν έκανα κάποιον άλλον.",
    "Ποτέ δεν έκανα ποτέ περήφανα το αλφάβητο.",
    "Ποτέ δεν γέλασα ποτέ τόσο σκληρά, κοίταξα τον εαυτό μου.",
    "Ποτέ δεν έχω διαλέξει μια γάμο στο κοινό.",
    "Ποτέ δεν ντύθηκα ποτέ ως το αντίθετο φύλο.",
    "Ποτέ δεν έχω ρυθμίσει ποτέ τα κουμπιά μου με βάση το ποιος είναι στο δωμάτιο.",
    "Ποτέ δεν έχω ξαφνιάσει μπροστά σε κάποιον που μου άρεσε.",
    "Ποτέ δεν έχω πηδήσει ποτέ σε μια πισίνα με ρούχα.",
    "Ποτέ δεν έχω δοκιμάσει ποτέ φεγγάρι.",
    "Ποτέ δεν έχω προσπαθήσει ποτέ να εντυπωσιάσω το φαινόμενο της γνώσης μου.",
    "Ποτέ δεν έστειλα ποτέ βρώμικο κείμενο σε λάθος άτομο.",
    "Ποτέ δεν έχω πετάξει ποτέ πρώτη θέση.",
    "Ποτέ δεν έκανα ποτέ χαρτί στο σπίτι κάποιου κατά τη διάρκεια του Halloween.",
    "Ποτέ δεν έχω οδηγήσει ποτέ μια αλλαγή ραβδιών.",
    "Ποτέ δεν έχω χρησιμοποιήσει ποτέ ψεύτικο αναγνωριστικό.",
    "Ποτέ δεν έχω πάει ποτέ σε γάμο προορισμού.",
    "Ποτέ δεν έχω χάσει ποτέ ένα υψηλό πέντε.",
    "Ποτέ δεν έχω μεταβιβάσει ποτέ ένα δώρο.",
    "Ποτέ δεν πήγα ποτέ ώρες χωρίς ντους.",
    "Ποτέ δεν έστειλα ξανά το φαγητό μου σε ένα εστιατόριο.",
    "Ποτέ δεν έχω σώσει ποτέ τη ζωή κάποιου άλλου.",
    "Ποτέ δεν είπα ψέματα στον καλύτερό μου φίλο για το ποιος ήμουν μαζί.",
    "Ποτέ δεν έχω πάει ποτέ σε μια Disneyland.",
    "Ποτέ δεν προσποιούμουν ότι ξέρω έναν ξένο γιατί ένιωθα ότι κάποιος με ακολουθούσε.",
    "Ποτέ δεν έχω ποτέ Δεν μου άρεσε κάτι που μαγειρεύω.",
    "Ποτέ δεν είχα ποτέ επίθεση πανικού.",
    "Ποτέ δεν έχω δοκιμάσει χαβιάρι.",
    "Ποτέ δεν έχω χρησιμοποιήσει ποτέ τον κωδικό πρόσβασης Netflix κάποιου άλλου.",
    "Ποτέ δεν κοιμήθηκα ποτέ στην τάξη.",
    "Ποτέ δεν απολύθηκα.",
    "Ποτέ δεν έχω δει ολόκληρη τηλεοπτική σειρά σε μια μέρα.",
    "Ποτέ δεν φίλησα ποτέ περισσότερα από ένα άτομα σε ώρες.",
    "Ποτέ δεν είχα ποτέ στάση μίας νύχτας και έμεινα για πρωινό.",
    "Ποτέ δεν έπρεπε ποτέ να κάνω μια ντροπή.",
    "Ποτέ δεν έχω χορέψει ποτέ σε ένα μπαρ.",
    "Ποτέ δεν με έδιωξαν ποτέ από μια παμπ / κλαμπ / μπαρ.",
    "Ποτέ δεν έχω παίξει ποτέ στο κλαμπ με ένα ξένο.",
    "Ποτέ δεν κοιμήθηκα ποτέ κατά τη διάρκεια του σεξ.",
    "Δεν έχω παίξει ποτέ ρόλους στο κρεβάτι.",
    "Ποτέ δεν έχω πάει ποτέ σε ένα strip club.",
    "Ποτέ δεν το έκανα ποτέ σε πάγκο κουζίνας.",
    "Ποτέ δεν κοιμήθηκα ποτέ με πανομοιότυπα δίδυμα.",
    "Ποτέ δεν κοιμήθηκα ποτέ με έναν σύντροφο φίλου.",
    "Ποτέ δεν έχω καταπιεί ποτέ με την πρώτη πίπα.",
    "Ποτέ δεν έχω πει ψέματα για τον \"αριθμό μου\" σε κάποιον που χρονολογώ.",
    "Ποτέ δεν με χειροπέδες.",
    "Ποτέ δεν είπα ψέματα για να προστατέψω έναν εξαπατημένο φίλο.",
    "Ποτέ δεν ξυπνήθηκα με κάποιον που μου έδινε το κεφάλι.",
    "Ποτέ δεν έχω κάνει ποτέ «τρελή αναζήτηση ρούχων» όταν κάποιος χτύπησε την πόρτα.",
    "Ποτέ δεν έχω φτιάξει ποτέ με τον μεγαλύτερο αδερφό ενός φίλου.",
    "Ποτέ δεν έχω τραβήξει γυμνές φωτογραφίες ενός φίλου.",
    "Ποτέ δεν έχω γίνει τόσο πεινασμένος που ορκίζομαι ότι δεν θα πιω ξανά.",
    "Ποτέ δεν φίλησα ποτέ κάποιον δημόσια.",
    "Ποτέ δεν είχα ποτέ δημόσια διαμάχη εραστή.",
    "Ποτέ δεν έχω παραλείψει σε λογαριασμό εστιατορίου.",
    "Ποτέ δεν έχω κερδίσει ποτέ τη λαχειοφόρο αγορά.",
    "Ποτέ δεν έπρεπε ποτέ να πάω στο δικαστήριο.",
    "Ποτέ δεν έπεσα ποτέ γάμος.",
    "Ποτέ δεν έχω παρακολουθήσει κάποιον στα κοινωνικά μέσα.",
    "Ποτέ δεν ανέβηκα ποτέ έξω από ένα παράθυρο.",
    "Ποτέ δεν γέλασα τόσο σκληρά που ξεφλούδισα το παντελόνι μου.",
    "Ποτέ δεν προσπάθησα να καπνίσω μαριχουάνα.",
    "Ποτέ δεν έχω πάρει τατουάζ.",
    "Ποτέ δεν έχω δημιουργήσει ποτέ ψεύτικο φίλο / φίλη.",
    "Ποτέ δεν προσποιούμουν ότι ήμουν άρρωστος ώστε οι άνθρωποι να με δώσουν προσοχή.",
    "Ποτέ δεν έχω ξοδέψει περισσότερα από $ σε ένα πορτοφόλι.",
    "Ποτέ δεν έχω ρίξει ποτέ ποτό σε κάποιον.",
    "Δεν έχω φορέσει ποτέ εσώρουχα κάποιου άλλου.",
    "Ποτέ δεν έχω δοκιμάσει ποτέ καταδύσεις.",
    "Ποτέ δεν συνελήφθηκα επειδή συμμετείχα σε μια διαδήλωση.",
    "Ποτέ δεν έχω κάνει πάρτι χωρίς διακοπή για περισσότερο από είκοσι τέσσερις ώρες."
];
var languages = keys(questions);
var language = (navigator.userLanguage || navigator.language).slice(0, 2);
var clanguage = ('; '+document.cookie).split(`; LANG=`).pop().split(';')[0];
if(languages.includes(clanguage)){
	language = clanguage;
}
function switchLang(lang){
	document.cookie = "LANG="+lang+"; expires="+new Date(Date.now()+315360000000).toUTCString()+ ";path=/";
	location.reload();
}
var questionsEx = languages.reduce((a,v) => ({ ...a, [v]: []}), {});
//used to show a prefix title to the question, also filters out these words from the question
var nhie = {
	en : "Never have I ever",
	cs : "Nikdy jsem",
	pt : "Eu nunca",
	fr : "Je n’ai jamais",
	de : "Ich habe noch nie",
	gr : "Ποτέ δεν"
}

function pickQuestion(){
	const excludeMap = questionsEx[language].reduce((all, item) => ({ ...all, [item]: true }), {});
	const uniqueQuestions = questions[language].filter((item) => !excludeMap?.[item]);
	var rand =  Math.floor(Math.random() * (uniqueQuestions.length - 1));
	window.questionsEx[language].push(uniqueQuestions[rand]);
	return [rand, uniqueQuestions[rand].split(nhie[language], 3)[1].trim()];
}
var players = {};
function addPlayer(name){
	window.players[name] = {
		questions : []
	};
}
function addPlayers(playerList){
	playerList.forEach((name) => {
		addPlayer(name);
	});
}
//call this when drawing a new question so we can keep track of who drank. Question is an ID of the question
function addScore(playerList, question){
	playerList.forEach((name) => {
		window.players[name].questions.push(question);
	});
}
function genScoreboard(){
	return Object.entries(window.players).sort(function(a,b){
		return b[1].questions.length-a[1].questions.length;
	});
}
