var questions = {};
questions.cs = [
    "Nikdy jsem nebyl(a) omylem zastaven(a) policií.",
    "Nikdy jsem sněhulákovi neudělal(a) prsa s pinďourem.",
    "Nikdy jsem nezažil(a), že by mi v práci proplatili celý den, aniž bych musel(a) hnout prstem.",
    "Nikdy jsem nebyl(a) náměsíčný/á.",
    "Nikdy jsem nepřistihl(a) své rodiče při sexu.",
    "Nikdy jsem si do čaje nedal(a) místo cukru sůl.",
    "Nikdy jsem neměl(a) nic zlomeného.",
    "Nikdy jsem neměl(a) rád(a), nebo nepil(a) rajčatový džus.",
    "Nikdy jsem omylem hlavou nerozbil(a) lustr.",
    "Nikdy jsem neomdlel(a).",
    "Nikdy jsem neposiloval(a).",
    "Nikdy jsem na sobě neměl(a) pyžamo.",
    "Nikdy jsem nic nesbíral(a) (např. známky).",
    "Nikdy jsem si nepodal(a) ruku s celebritou.",
    "Nikdy jsem nezažil(a), že by mě ve spánku pozvracel pes.",
    "Nikdy jsem neulovil(a) živou rybu.",
    "Nikdy jsem si nevyrazil(a) dech.",
    "Nikdy jsem netoužil(a) po sexu s nějakou celebritou.",
    "Nikdy jsem neviděl(a) živou světlušku.",
    "Nikdy jsem neviděl(a) ducha, ani nezažil(a) nic jiného, nadpřirozeného.",
    "Nikdy jsem v životě nemusel(a) bojovat o život.",
    "Nikdy jsem se nenaučil(a) lyžovat.",
    "Nikdy jsem nebyl(a) na Slovensku.",
    "Nikdy jsem si nepřivřel(a) prst do dveří.",
    "Nikdy jsem nevyrazil(a) na nákup omylem bez peněz.",
    "Nikdy jsem nevykouřil(a) víc jak 3 cigarety denně.",
    "Nikdy jsem omylem nesnědl(a) mouchu.",
    "Nikdy jsem nebyl(a) vzrušený/á z toho, když někdo okolo mě měl sex.",
    "Nikdy jsem po silnici (mimo dálnici) nejel(a) víc jak 100 km/hod.",
    "Nikdy jsem nechodil(a) po bytě v botech od bláta.",
    "Nikdy jsem se jen tak nepodíval(a) na porno.",
    "Nikdy jsem na vysvědčení neměl(a) horší známku než trojku.",
    "Nikdy jsem nejedl(a) žádné zvíře zaživa.",
    "Nikdy jsem nikomu nic neudělal(a) ve spánku (např. pomalování obličeje).",
    "Nikdy jsem nezažil(a) jídlo při svíčkách.",
    "Nikdy jsem na nikoho nenalíčil(a) past.",
    "Nikdy jsem si nezkazil(a) účes tím, že jsem se vlastoručně ostříhal(a).",
    "Nikdy jsem se na veřejnosti nekoupal(a) mezi lidmi nahý/á (mimo dětství).",
    "Nikdy jsem minimálně do pěti let nevěděl(a) o tom, že existuje sex.",
    "Nikdy jsem nebyl(a) vzhůru déle než 48 hodin.",
    "Nikdy jsem nedokázal(a) nejíst víc jak 24 hodin.",
    "Nikdy jsem si ilegálně nestáhl(a) nějakou věc.",
    "Nikdy jsem si v životě nerozbil(a) víc jak 2 mobily.",
    "Nikdy jsem nevyhodil(a) svůj mobil do dáli a totálně ho nerozsekal(a).",
    "Nikdy jsem nezjistil(a), jak obratně nakrájet cibuli na kostičky.",
    "Nikdy jsem se se svým/svou dosavadní nejlepší kamarádkou/kamarádem nepohádal(a).",
    "Nikdy jsem neudělal(a) to, že bych nalezenou peněženku nevrátil(a), nebo nenahlásil(a).",
    "Nikdy jsem se nesnažil(a) někoho opít.",
    "Nikdy jsem neměl(a) kamaráda/kamarádku, co by jeli na drogách (těžších než marihuana).",
    "Nikdy jsem nešmíroval(a) někoho nahého pod vodou.",
    "Nikdy jsem si nechatoval(a) s jinými lidmi během sexu.",
    "Nikdy jsem neměl(a) pohlavní nemoc.",
    "Nikdy jsem neprojížděl(a) svému nejlepšímu kamarádovi/kamarádce mobil (aniž by o tom věděl(a)).",
    "Nikdy jsem úmyslně nesnědl(a) nic zkaženého.",
    "Nikdy jsem nebyl(a) na rande s více jak jedním člověkem.",
    "Nikdy jsem se neopil(a) do bezvědomí.",
    "Nikdy jsem si nic nekupoval(a) v sexshopu.",
    "Nikdy jsem se nechlubil(a), že jsem měl(a) sex s někým, když to nebyla pravda.",
    "Nikdy jsem nezažil(a), že by mi někdo nabídl, že by se mnou chtěl mít sex (počítá se i partner).",
    "Nikdy jsem se po 12. roce života nevyčůral(a) do bazénu.",
    "Nikdy jsem nezkoušel(a) tvrdší drogy, než je tráva.",
    "Nikdy jsem si nevolal(a) s někým během sexu.",
    "Nikdy jsem z legrace fyzicky neubližoval(a) zvířatům.",
    "Nikdy jsem nic naschvál v práci nerozbil(a).",
    "Nikdy jsem nepodvedl(a) svou polovičku.",
    "Nikdy jsem nikomu nezůstal(a) dlužníkem peněz.",
    "Nikdy jsem se na internetu nevydával(a) za někoho jiného.",
    "Nikdy jsem si během sprchování nepořizoval(a) selfie.",
    "Nikdy jsem neměl(a) víc jak 10 sexuálních partnerů.",
    "Nikdy jsem nepoužíval(a) vlastoručně vyráběnou, erotickou hračku.",
    "Nikdy jsem nepředstíral(a), že se s kamarády dobře bavím a potom je druhý den nepomlouval(a).",
    "Nikdy jsem před jiným člověkem ze srandy neponížil(a) svého nejlepšího kamaráda/kamarádku.",
    "Nikdy jsem se s dítětem nekoukal(a) na nic erotického.",
    "Nikdy jsem nezvracel(a) ožralý/á ve spánku.",
    "Nikdy jsem sexuálně nezneužil(a) partnera, zatímco spal.",
    "Nikdy jsem si nefotil(a) svoje přirození.",
    "Nikdy jsem nespal(a) s nikým pod 13 let.",
    "Nikdy jsem nikomu neukradl(a) peníze.",
    "Nikdy jsem nikomu neplivl(a) do jídla.",
    "Nikdy jsem nedal(a) živého tvora do mikrovlnky a tím nezabil(a).",
    "Nikdy jsem svému nejlepšímu kamarádovi nepřebral(a) partnera.",
    "Nikdy jsem nebyl(a) sprostý/á na svoje rodiče.",
    "Nikdy jsem za zády nepomlouval(a) svého nejlepšího kamaráda/kamarádku, i když jsem se před ním tvářil(a), že je vše v pořádku.",
    "Nikdy jsem nikomu neřekl(a), že spousta mých vztahů byl(a) jen kvůli tomu, abych nebyl(a) v životě bez partnera.",
    "Nikdy jsem na nikoho úspěšně nehodil(a) svůj velký prohřešek.",
    "Nikdy jsem naschvál malému dítěti nedal(a) něco odporného k jídlu, co normální lidi nejedí (např. hmyz).",
    "Nikdy jsem nepomyslel(a) na to, že bych zahnul(a) své dosavadní polovičce.",
    "Nikdy jsem neměl(a) sex s člověkem, který nevěděl, že trpím pohlavní nemocí.",
    "Nikdy jsem nebyl(a) na testu proti HIV i když jsem měl(a) více jak 15 sexuálních partnerů.",
    "Nikdy jsem nikomu neřekl(a) o pravdě, že mě sexuálně přitahuje stejné pohlaví.",
    "Nikdy jsem nikomu neřekl(a), že bych nechtěl(a) mít děti i když je to pravda.",
    "Nikdy jsem neměl(a) v úmyslu dát peníze na charitu i když bych měl(a) na účtě více jak 100 milionů korun.",
    "Nikdy jsem nikomu neřekl(a), že nemám moc kamarádské pouto se svými rodiči, i když je to pravda.",
    "Nikdy jsem s někým nespal(a) jen kvůli tomu, abych zahnal(a) svoje sexuální choutky, i když si o mně dotyčný myslel něco jiného.",
    "Nikdy jsem nikomu neřekl(a) &#8220;miluji tě&#8221;.",
    "Nikdy jsem se v dospělosti nerozbrečel(a) u doktora.",
    "Nikdy jsem nedokázal(a) všem svým nejbližším říct, že mám nějaké fyzické postižení.",
    "Nikdy jsem nepomyslel(a) na to, že bych chtěl(a), aby někdo z mé rodiny zemřel, abych měl(a) nárok na nemovitost.",
    "Nikdy jsem nešířil(a) největší tajemství toho, kdo mi věřil.",
    "Nikdy jsem v análu neměl(a) žádnou erotickou pomůcku.",
    "Nikdy jsem se na záchodě neutřela ruličkou od papíru.",
    "Nikdy jsem nepředváděla nějaký klip když jsem byl/a sama doma.",
    "Nikdy jsem nehodil odpadek do trávy.",
    "Nikdy jsem neměl pohlavní styk.",
    "Nikdy jsem si nečistil zuby prstem.",
    "Nikdy jsem neukradl peníze.",
    "Nikdy jsem nešáhl opačému pohlaví za zadek.",
    "Nikdy jsem se nechtěl vyspat s youtuberem.",
    "Nikdy jsem neřekl sprosté slovo před učitelem.",
    "Nikdy jsem kamarádovi nepoblil boty (xD).",
    "Nikdy jsem nedal opačnému pohlaví facku.",
    "Nikdy jsem neběhal nahý po domě, bytě.",
    "Nikdy jsem neukradl něco na návštěvě.",
    "Nikdy jsem nezkoušel odemknout mobil jazykem.",
    "Nikdy jsem si pořádně nahlas neprdl na veřejnosti.",
    "Nikdy jsem se nepozvracel na silvestra.",
    "Nikdy jsem neviděl youtubera.",
    "Nikdy jsem nenadával na oblíbeného youtubera.",
    "Nikdy jsem neměl nejvíc likeovaný komentář u videa.",
    "Nikdy jsem netočil video na youtube.",
    "Nikdy jsem neměl děsnou chut na něco co nemám rád.",
    "Nikdy jsem neusnul u filmu.",
    "Nikdy jsem nechtěl utéct z domu.",
    "Nikdy jsem nezkoušel helium.",
    "Nikdy jsem se nepohádal v obchodě se zaměstanavatelem. (hlídačkou,prodavačkou)",
    "Nikdy jsem neměl myšlenku o tom že se zabiju.",
    "Nikdy jsem se nepočural smíchy.",
    "Nikdy jsem neměl pindíka. (xD)",
    "Nikdy jsem se nevyčural do vany nebo do sprchy.",
    "Nikdy jsem si nedával nohy za hlavu.",
    "Nikdy jsem si nečuchl k mému prdu.",
    "Nikdy jsem nedal dislike Gogovy.",
    "Nikdy jsem na sobě neměl make-up.",
    "Nikdy jsem neutopil rybu.",
    "Nikdy jsem se pořádně nevykakal.",
    "Nikdy jsem nebyl v kině na hororu.",
    "Nikdy jsem se nevysmrkal do ponošky.",
    "Nikdy jsem nedělal balonky z kondomů..",
    "Nikdy jsem nepromluvil rasisticky.",
    "Nikdy jsem neurážel Miloše Zemana.",
    "Nikdy jsem nekouřil.",
    "Nikdy jsem se nelíbal se stejným pohlavím.",
    "Nikdy jsem se nelíbal se spolužákem.",
    "Nikdy jsem nehrál Minecraft.",
    "Nikdy jsem neměla záchvat smíchu z videií FattyhoPillowa.",
    "Nikdy jsem nezpíval song od Mishovy Šílenosti.",
    "Nikdy jsem nikomu nedal přes držku.",
    "Nikdy jsem nedostal přes držku."
];
questions.en = [
    "Never have I ever gone skinny dipping.",
    "Never have I ever gone on a blind date.",
    "Never have I ever creeped an ex on social media.",
    "Never have I ever been hungover.",
    "Never have I ever kissed my best friend.",
    "Never have I ever ghosted someone.",
    "Never have I ever gotten a speeding ticket.",
    "Never have I ever slid into someone's DMs.",
    "Never have I ever dined and dashed.",
    "Never have I ever used a fake ID.",
    "Never have I ever had a crush on a teacher.",
    "Never have I ever been in love.",
    "Never have I ever made out in a public place.",
    "Never have I ever gotten into a physical fight.",
    "Never have I ever had an alcoholic drink.",
    "Never have I ever played spin the bottle.",
    "Never have I ever snooped through someone's phone.",
    "Never have I ever snuck into a movie theater.",
    "Never have I ever kissed a friend's ex.",
    "Never have I ever told someone \"I love you\" without meaning it.",
    "Never have I ever been called a player.",
    "Never have I ever smoked a cigarette.",
    "Never have I ever given a lap dance.",
    "Never have I ever gotten a lap dance.",
    "Never have I ever cheated on a test.",
    "Never have I ever used a dating app.",
    "Never have I ever kissed more than one person in hours.",
    "Never have I ever cheated on someone.",
    "Never have I ever been cheated on.",
    "Never have I ever sent a racy text to the wrong person.",
    "Never have I ever had a negative bank account balance.",
    "Never have I ever played strip poker.",
    "Never have I ever been arrested.",
    "Never have I ever been expelled.",
    "Never have I ever stolen anything.",
    "Never have I ever gotten a hickey.",
    "Never have I ever been fired.",
    "Never have I ever made out in a movie theater.",
    "Never have I ever dated someone older than me.",
    "Never have I ever dated someone younger than me.",
    "Never have I ever broken the law.",
    "Never have I ever been to a nude beach.",
    "Never have I ever stood a date up.",
    "Never have I ever stayed in a relationship that I really wasn’t feeling.",
    "Never have I ever given someone a fake phone number.",
    "Never have I ever lied to someone in this room.",
    "Never have I ever broken up with someone over text.",
    "Never have I ever had a crush on an SO’s best friend.",
    "Never have I ever shoplifted.",
    "Never have I ever seen a ghost.",
    "Never have I ever told a secret I wasn’t supposed to share.",
    "Never have I ever had a friend with benefits.",
    "Never have I ever intentionally started a fight between other people.",
    "Never have I ever dated more than one person at once.",
    "Never have I ever spent money that wasn’t mine to spend.",
    "Never have I ever had a relationship last less than a month.",
    "Never have I ever had a relationship last longer than a year.",
    "Never have I ever gotten an unexpected piercing.",
    "Never have I ever found a dumb excuse to text an ex.",
    "Never have I ever fallen in love at first sight.",
    "Never have I ever kissed someone I just met.",
    "Never have I ever kept a crush secret from people in this room.",
    "Never have I ever been in love with someone without them knowing.",
    "Never have I ever been in an open relationship.",
    "Never have I ever fantasized about getting back with an ex.",
    "Never have I ever helped a friend lie by being their alibi.",
    "Never have I ever seriously thought about marrying someone.",
    "Never have I ever had a totally online relationship.",
    "Never have I ever flirted just to get something I wanted.",
    "Never have I ever tried guessing someone’s password.",
    "Never have I ever been caught lying.",
    "Never have I ever farted in front of a significant other.",
    "Never have I ever peed in the shower.",
    "Never have I ever peed in a pool.",
    "Never have I ever eaten a carton of ice cream.",
    "Never have I ever cheated in a board game.",
    "Never have I ever cheated in a card game.",
    "Never have I ever screamed during a scary movie.",
    "Never have I ever laughed so hard I spit out my drink.",
    "Never have I ever been sent to the principal's office.",
    "Never have I ever clogged a toilet.",
    "Never have I ever toilet-papered someone's house.",
    "Never have I ever worn something I took out of my dirty laundry.",
    "Never have I ever vomited after a roller coaster ride.",
    "Never have I ever watched an entire television series in a day.",
    "Never have I ever said “I love you” to someone by accident.",
    "Never have I ever walked in on my parents having sex.",
    "Never have I ever lied while playing this game.",
    "Never have I ever Googled myself.",
    "Never have I ever had a pet name for an SO.",
    "Never have I ever been given a pet name by an SO.",
    "Never have I ever had a dirty dream about a super unexpected person.",
    "Never have I ever been accused of sharing too much on social media.",
    "Never have I ever created a fake social media account.",
    "Never have I ever run out of gas while driving.",
    "Never have I ever gone to a party I wasn’t invited to.",
    "Never have I ever dated someone super annoying only because they’re cute.",
    "Never have I ever lied on a first date.",
    "Never have I ever used someone else's toothbrush.",
    "Never have I ever pretended to be on the phone.",
    "Never have I ever enjoyed a smell I’m supposed to find gross.",
    "Never have I ever been on TV for an embarrassing reason.",
    "Never have I ever gone several days without showering.",
    "Never have I ever turned my underwear inside out so I don’t have to wash it.",
    "Never have I ever lied about what I was doing on social media.",
    "Never have I ever been told I snore loudly.",
    "Never have I ever had a crush on a friend's sibling.",
    "Never have I ever eaten a carton of ice cream.",
    "Never have I ever gone commando.",
    "Never have I ever shaved my head.",
    "Never have I ever gotten a tattoo.",
    "Never have I ever broken a bone.",
    "Never have I ever been to a bachelorette party or bachelor party.",
    "Never have I ever gotten heated during a family game night.",
    "Never have I ever met a celebrity.",
    "Never have I ever had a surprise party thrown for me.",
    "Never have I ever travelled solo.",
    "Never have I ever eaten whipped cream straight out of the can.",
    "Never have I ever auditioned for a reality television show.",
    "Never have I ever told my parents I was staying at a friend's house but was really somewhere else.",
    "Never have I ever been to a psychic.",
    "Never have I ever lived alone.",
    "Never have I ever sang karaoke.",
    "Never have I ever stayed overnight in the hospital.",
    "Never have I ever deleted a post because it didn't get enough likes.",
    "Never have I ever stayed up all night.",
    "Never have I ever been on a cruise.",
    "Never have I ever lost a bet.",
    "Never have I ever gotten in a car accident.",
    "Never have I ever rode a motorcycle.",
    "Never have I ever pretended to be sick to get out of school.",
    "Never have I ever beaten a video game.",
    "Never have I ever cried at school.",
    "Never have I ever talked to a family member about my sex life.",
    "Never have I ever been to Mexico.",
    "Never have I ever eaten caviar.",
    "Never have I ever used someone else's Netflix password.",
    "Never have I ever fallen asleep in class.",
    "Never have I ever dyed my hair.",
    "Never have I ever read an entire book in a day.",
    "Never have I ever seen an alligator in real life.",
    "Never have I ever re-gifted a gift.",
    "Never have I ever sleepwalked.",
    "Never have I ever gone snowboarding.",
    "Never have I ever been awake for hours (or more) straight.",
    "Never have I ever broken up with someone in a way I regret.",
    "Never have I ever fainted.",
    "Never have I ever had a fight with a SO in public.",
    "Never have I ever knowingly spread a rumor.",
    "Never have I ever cried at school.",
    "Never have I ever been somewhere I was sure was haunted.",
    "Never have I ever cut my own hair.",
    "Never have I ever lied to get out of plans with friends."
];

var languages = keys(questions);
var language = (navigator.userLanguage || navigator.language).slice(0, 2);
var clanguage = ('; '+document.cookie).split(`; LANG=`).pop().split(';')[0];
if(languages.includes(clanguage)){
	language = clanguage;
}
function switchLang(lang){
	document.cookie = "LANG="+lang+"; expires="+new Date(Date.now()+315360000000).toUTCString()+ ";path=/";
	location.reload();
}
var questionsEx = languages.reduce((a,v) => ({ ...a, [v]: []}), {});
//used to show a prefix title to the question, also filters out these words from the question
var nhie = {
	en : "Never have I ever",
	cs : "Nikdy jsem"
}

function pickQuestion(){
	const excludeMap = questionsEx[language].reduce((all, item) => ({ ...all, [item]: true }), {});
	const uniqueQuestions = questions[language].filter((item) => !excludeMap?.[item]);
	var rand =  Math.floor(Math.random() * (uniqueQuestions.length - 1));
	window.questionsEx[language].push(uniqueQuestions[rand]);
	return [rand, uniqueQuestions[rand].split(nhie[language], 3)[1].trim()];
}
var players = {};
function addPlayer(name){
	window.players[name] = {
		questions : []
	};
}
function addPlayers(playerList){
	playerList.forEach((name) => {
		addPlayer(name);
	});
}
//call this when drawing a new question so we can keep track of who drank. Question is an ID of the question
function addScore(playerList, question){
	playerList.forEach((name) => {
		window.players[name].questions.push(question);
	});
}
function genScoreboard(){
	return Object.entries(window.players).sort(function(a,b){
		return b[1].questions.length-a[1].questions.length;
	});
}
